/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.view;

import com.incosyz.sms.clientcontroller.Generator;
import com.incosyz.sms.clientcontroller.UserControllerClient;
import com.incosyz.sms.model.UserModel;
import com.incosyz.sms.panel.SignUpRow;
import static com.incosyz.sms.view.Home.img;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Date : Nov 18, 2015 Time : 5:23:49 PM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class AddUser extends javax.swing.JDialog {

    /**
     * Creates new form ManageUsers
     */
    public AddUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(img);
        defaultTableModel = (DefaultTableModel) userTable.getModel();
        try {
            getUsers();
        } catch (NotBoundException | MalformedURLException | ClassNotFoundException | SQLException | RemoteException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        typeCombo = new javax.swing.JComboBox();
        doneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Samagi Traders | Sales Management System | Manage User Detail");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("User Type :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 330, 140, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 190, 140, 30);
        jPanel1.add(passwordText);
        passwordText.setBounds(40, 220, 240, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Confirm Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 260, 140, 30);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(40, 290, 240, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Username :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 140, 30);
        jPanel1.add(usernameText);
        usernameText.setBounds(40, 150, 240, 30);

        typeCombo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Local Account", "Admin Account" }));
        jPanel1.add(typeCombo);
        typeCombo.setBounds(40, 360, 240, 30);

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/done.jpg"))); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doneButton);
        doneButton.setBounds(170, 420, 110, 50);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Type"
            }
        ));
        userTable.setRowHeight(25);
        jScrollPane1.setViewportView(userTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(320, 150, 452, 320);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Samagi Traders - Create New User Accounts");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 30, 350, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Sales Management System");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 60, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        UserModel userModel = new UserModel();
        try {
            String generateId = Generator.generateId("Users", "userId", "U", 3);
            userModel.setUserId(generateId);
            userModel.setUserName(usernameText.getText());

            String password = String.valueOf(passwordText.getPassword());

            userModel.setPassword(password);
            userModel.setUserType((String) typeCombo.getSelectedItem());
            boolean addUser = UserControllerClient.addUser(userModel);
            if (addUser) {
                setUser(userModel);
                JOptionPane.showMessageDialog(this, "User added successfully !");
            }
        } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUser dialog = new AddUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel defaultTableModel;
    private ArrayList<UserModel> users;

    public void getUsers() throws NotBoundException, MalformedURLException, ClassNotFoundException, SQLException, RemoteException {
        ArrayList<UserModel> users = UserControllerClient.getUsers();
        setUser(users);
    }

    public void setUser(ArrayList<UserModel> users) {
        this.users = users;
        defaultTableModel.setRowCount(0);
        for (UserModel userModel : users) {
            setUser(userModel);
        }   
    }

    public void setUser(UserModel model) {
        Object[] objects = {model.getUserName(), model.getPassword(), model.getUserType()};
        defaultTableModel.addRow(objects);
    }

}
