/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.view;

import com.incosyz.sms.clientcontroller.ChequeControllerClient;
import com.incosyz.sms.clientcontroller.Generator;
import com.incosyz.sms.clientcontroller.SaleControllerImplClient;
import com.incosyz.sms.config.Setting;
import com.incosyz.sms.dialog.CashSalesReport;
import com.incosyz.sms.mixmodel.GETOrderModel;
import com.incosyz.sms.mixmodel.StockModel;
import com.incosyz.sms.model.BikeModel;
import com.incosyz.sms.model.CheckModel;
import com.incosyz.sms.model.CustomerModel;
import com.incosyz.sms.model.HomePhoneModel;
import com.incosyz.sms.model.MobileModel;
import com.incosyz.sms.model.OrderModel;
import com.incosyz.sms.report.ReportGenerator;
import java.awt.Container;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 * Date : Nov 24, 2015 Time : 3:21:11 PM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class DailySalesReport extends javax.swing.JFrame {

    static JasperReport cashSale_report;

    public static String REPORT_PATH = "./src/com/incosyz/sms/report/";

    /**
     * Creates new form DailySalesReport
     */
    public DailySalesReport() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            if (cashSale_report == null) {
                cashSale_report = JasperCompileManager.compileReport(REPORT_PATH + "DailySalesReportCashSale.jrxml");
            }
        } catch (JRException ex) {
            Logger.getLogger(DailySalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        date1Text = new javax.swing.JTextField();
        amount1Text = new javax.swing.JTextField();
        chequeNo1Text = new javax.swing.JTextField();
        bankNameText = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        date2Text = new javax.swing.JTextField();
        chequeNo2Text = new javax.swing.JTextField();
        amount2Text = new javax.swing.JTextField();
        bankNameText1 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        homeText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        provinceText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        datePurchaseText = new javax.swing.JTextField();
        roundNoText = new javax.swing.JTextField();
        modelColorText = new javax.swing.JTextField();
        engineNoText = new javax.swing.JTextField();
        profomaInvoiceNoText = new javax.swing.JTextField();
        customerPriceText = new javax.swing.JTextField();
        netAmountText = new javax.swing.JTextField();
        lessCommission = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        reportNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dateReport = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sales Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 230, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cash Sales Motor Bike");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 10, 350, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Name Mr, Mrs :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 100, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Motor Bike Details :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 350, 210, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Mobile No :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 170, 100, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 170, 100, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Home / Office :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 110, 100, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("NIC No :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 230, 100, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Province :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 230, 100, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Date of Purchase :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 290, 110, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Round No :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 380, 110, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Remark :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 440, 210, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Profoma Invoice No");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(210, 440, 110, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Engine No Last 4:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 440, 110, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Model / Color :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(210, 380, 110, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Customer Price LKR");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 500, 140, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("New Amount LKR");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(210, 500, 110, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Less Commission");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 560, 110, 20);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Customer Details :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 80, 210, 20);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Remittance Details :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(400, 180, 210, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Samagi Traders - Daily Sales Report ");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(30, 10, 350, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/viewReport.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(830, 560, 110, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cheque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Date");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 30, 110, 20);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Cheque No");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(130, 30, 110, 20);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Amount Rs");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(270, 30, 110, 20);
        jPanel2.add(date1Text);
        date1Text.setBounds(10, 50, 110, 30);
        jPanel2.add(amount1Text);
        amount1Text.setBounds(270, 50, 120, 30);
        jPanel2.add(chequeNo1Text);
        chequeNo1Text.setBounds(130, 50, 130, 30);

        bankNameText.setEditable(true);
        bankNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bankNameText.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amana Bank PLC", "Axis Bank Ltd.", "Bank of Ceylon", "Cargills Bank Ltd.", "Citibank N.A.", "Commercial Bank of Ceylon PLC", "Deutsche Bank AG", "DFCC Bank PLC", "Habib Bank Ltd.", "Hatton National Bank PLC", "ICICI Bank Ltd.", "Indian Bank", "Indian Overseas Bank", "National Development Bank PLC", "Nations Trust Bank PLC", "Pan Asia Banking Corporation PLC", "People's Bank", "Public Bank Berhad", "Sampath Bank PLC", "Seylan Bank PLC", "Standard Chartered Bank", "Union Bank of Colombo PLC" }));
        jPanel2.add(bankNameText);
        bankNameText.setBounds(400, 50, 130, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setText("Bank Name ");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(400, 30, 110, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 220, 540, 100);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Date");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(10, 30, 110, 20);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setText("Cheque No");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(130, 30, 110, 20);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("Bank Name ");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(400, 30, 110, 20);
        jPanel3.add(date2Text);
        date2Text.setBounds(10, 50, 110, 30);
        jPanel3.add(chequeNo2Text);
        chequeNo2Text.setBounds(130, 50, 130, 30);
        jPanel3.add(amount2Text);
        amount2Text.setBounds(270, 50, 120, 30);

        bankNameText1.setEditable(true);
        bankNameText1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bankNameText1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amana Bank PLC", "Axis Bank Ltd.", "Bank of Ceylon", "Cargills Bank Ltd.", "Citibank N.A.", "Commercial Bank of Ceylon PLC", "Deutsche Bank AG", "DFCC Bank PLC", "Habib Bank Ltd.", "Hatton National Bank PLC", "ICICI Bank Ltd.", "Indian Bank", "Indian Overseas Bank", "National Development Bank PLC", "Nations Trust Bank PLC", "Pan Asia Banking Corporation PLC", "People's Bank", "Public Bank Berhad", "Sampath Bank PLC", "Seylan Bank PLC", "Standard Chartered Bank", "Union Bank of Colombo PLC" }));
        jPanel3.add(bankNameText1);
        bankNameText1.setBounds(400, 50, 130, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("Amount Rs");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(270, 30, 110, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(400, 330, 540, 100);
        jPanel1.add(nameText);
        nameText.setBounds(30, 130, 150, 30);
        jPanel1.add(homeText);
        homeText.setBounds(210, 130, 150, 30);
        jPanel1.add(addressText);
        addressText.setBounds(210, 190, 150, 30);
        jPanel1.add(mobileText);
        mobileText.setBounds(30, 190, 150, 30);
        jPanel1.add(provinceText);
        provinceText.setBounds(30, 250, 150, 30);
        jPanel1.add(nicText);
        nicText.setBounds(210, 250, 150, 30);
        jPanel1.add(datePurchaseText);
        datePurchaseText.setBounds(30, 310, 150, 30);
        jPanel1.add(roundNoText);
        roundNoText.setBounds(30, 400, 150, 30);
        jPanel1.add(modelColorText);
        modelColorText.setBounds(210, 400, 150, 30);
        jPanel1.add(engineNoText);
        engineNoText.setBounds(30, 460, 150, 30);
        jPanel1.add(profomaInvoiceNoText);
        profomaInvoiceNoText.setBounds(210, 460, 150, 30);
        jPanel1.add(customerPriceText);
        customerPriceText.setBounds(30, 520, 150, 30);
        jPanel1.add(netAmountText);
        netAmountText.setBounds(210, 520, 150, 30);
        jPanel1.add(lessCommission);
        lessCommission.setBounds(30, 580, 150, 30);
        jPanel1.add(jTextField18);
        jTextField18.setBounds(410, 460, 390, 30);
        jPanel1.add(jTextField19);
        jTextField19.setBounds(410, 490, 390, 30);
        jPanel1.add(jTextField20);
        jTextField20.setBounds(410, 520, 390, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Report No :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(400, 100, 100, 20);
        jPanel1.add(reportNo);
        reportNo.setBounds(400, 120, 150, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Report Date :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(560, 100, 100, 20);
        jPanel1.add(dateReport);
        dateReport.setBounds(560, 120, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = nameText.getText();
        String mobile = mobileText.getText();
        String home = homeText.getText();
        String address = addressText.getText();
        String province = provinceText.getText();
        String nic = nicText.getText();
        String pdate = datePurchaseText.getText();

        String roundNo = roundNoText.getText();
        String modelColor = modelColorText.getText();
        String engineNo = engineNoText.getText();
        String profomaInvoiceNo = profomaInvoiceNoText.getText();
        String customerPrice = customerPriceText.getText();
        String lessCommision = lessCommission.getText();
        String netAmount = netAmountText.getText();

        String date1 = date1Text.getText();
        String date2 = date2Text.getText();
        String chequeNo1 = chequeNo1Text.getText();
        String chequeNo2 = chequeNo2Text.getText();
        String amount1 = amount1Text.getText();
        String amount2 = amount2Text.getText();
        String bankName1 = bankNameText.getSelectedItem().toString();
        String bankName2 = bankNameText1.getSelectedItem().toString();

//        try {
//            boolean exists = ChequeControllerClient.isExist(chequeNo1);
//            if (!exists) {
//                CheckModel checkModel = new CheckModel();
//
//                String generateId = Generator.generateId("Cheque", "chequeId", "C", 3);
//                checkModel.setChequeId(generateId);
//                checkModel.setCheckNo(chequeNo1);
//                checkModel.setChequeDate(date1);
//                checkModel.setAmount(amount1);
//                checkModel.setBankName(bankName1);
//                checkModel.setNote(roundNo);
//                checkModel.setIssuedBy("TVS");
//                checkModel.setIsIssued("1");
//                ChequeControllerClient.addCheque(checkModel);
//            }
//
//            boolean exists2 = ChequeControllerClient.isExist(chequeNo1);
//            if (!exists2) {
//                CheckModel checkModel1 = new CheckModel();
//
//                String generateId = Generator.generateId("Cheque", "chequeId", "C", 3);
//                checkModel1.setChequeId(generateId);
//                checkModel1.setCheckNo(chequeNo2);
//                checkModel1.setChequeDate(date2);
//                checkModel1.setAmount(amount2);
//                checkModel1.setBankName(bankName2);
//                checkModel1.setNote(roundNo);
//                checkModel1.setIssuedBy("TVS");
//                checkModel1.setIsIssued("1");
//                ChequeControllerClient.addCheque(checkModel1);
//            }
//
//        } catch (NotBoundException | MalformedURLException | ClassNotFoundException | SQLException | RemoteException ex) {
//            Logger.getLogger(DailySalesReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
        String rNo = reportNo.getText();

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String rDate = dateFormat.format(dateReport.getDate());

        try {
            Map<String, Object> map = new HashMap<>();

            Setting s = new Setting();
            String companyName = s.getProperty("NAME");
            String code = s.getProperty("CODE");

            map.put("dealerName", companyName);
            map.put("dealerCode", code);
            map.put("date", rDate);
            map.put("reportNo", rNo);

            map.put("name", name);
            map.put("mobile", mobile);
            map.put("home", home);
            map.put("address", address);
            map.put("province", province);
            map.put("nic", nic);
            map.put("pdate", pdate);

//            map.put("poNo", "2015-05-05");
//            map.put("roundNo", "2015-05-05");
//            map.put("modelColor", "2015-05-05");
//            map.put("engineNo", "2015-05-05");
//
            map.put("roundNo", roundNo);
            map.put("modelColor", modelColor);
            map.put("engineNo", engineNo);
            map.put("profomaInvoiceNo", profomaInvoiceNo);
            map.put("customerPrice", customerPrice);
            map.put("lessCommission", lessCommision);
            map.put("netAmount", netAmount);

            map.put("date1", date1);
            map.put("date2", date2);
            map.put("chequeNo1", chequeNo1);
            map.put("chequeNo2", chequeNo2);
            map.put("chequeAmount1", amount1);
            map.put("chequeAmount2", amount2);

            Container generateReport = ReportGenerator.generateReport(cashSale_report, null, map, null);
            CashSalesReport cashSalesReport = new CashSalesReport(generateReport);
            cashSalesReport.setVisible(true);
            try {
                SaleControllerImplClient.reported(orderId);
            } catch (MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(DailySalesReport.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (JRException ex) {
            Logger.getLogger(CashSalesReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DailySalesReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(DailySalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailySalesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField amount1Text;
    private javax.swing.JTextField amount2Text;
    private javax.swing.JComboBox bankNameText;
    private javax.swing.JComboBox bankNameText1;
    private javax.swing.JTextField chequeNo1Text;
    private javax.swing.JTextField chequeNo2Text;
    private javax.swing.JTextField customerPriceText;
    private javax.swing.JTextField date1Text;
    private javax.swing.JTextField date2Text;
    private javax.swing.JTextField datePurchaseText;
    private org.jdesktop.swingx.JXDatePicker dateReport;
    private javax.swing.JTextField engineNoText;
    private javax.swing.JTextField homeText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField lessCommission;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField modelColorText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField netAmountText;
    private javax.swing.JTextField nicText;
    private javax.swing.JTextField profomaInvoiceNoText;
    private javax.swing.JTextField provinceText;
    private javax.swing.JTextField reportNo;
    private javax.swing.JTextField roundNoText;
    // End of variables declaration//GEN-END:variables

    private String orderId;

    public void setDetail(GETOrderModel gETOrderModel) {
        CustomerModel customerModel = gETOrderModel.getCustomerModel();
        ArrayList<HomePhoneModel> homePhoneModel = gETOrderModel.getHomePhoneModels();
        ArrayList<MobileModel> mobileModels = gETOrderModel.getMobileModels();
        OrderModel orderModel = gETOrderModel.getOrderModel();
        BikeModel bikeModel = gETOrderModel.getBikeModel();
        StockModel stockModel = gETOrderModel.getStockModel();

        orderId = orderModel.getOrderId();

        if (customerModel != null) {
            nameText.setText(customerModel.getCustomerName());

            if (homePhoneModel.size() > 0) {
                homeText.setText(homePhoneModel.get(0).getHomePhoneNo());
            }

            if (mobileModels.size() > 0) {
                mobileText.setText(mobileModels.get(0).getMobileNo());
            }

            addressText.setText(customerModel.getAddressLineOne() + ", " + customerModel.getAddressLineTwo() + ", " + customerModel.getAddressLineThree());
            provinceText.setText("");
            nicText.setText(customerModel.getNicNo());
            datePurchaseText.setText(orderModel.getOrderDate());

            roundNoText.setText(orderModel.getRoundNo());
            modelColorText.setText(stockModel.getColour());

            if (stockModel.getEngineNo().length() > 4) {
                engineNoText.setText(stockModel.getEngineNo().substring(stockModel.getEngineNo().length() - 4, stockModel.getEngineNo().length()));
            } else {
                engineNoText.setText(stockModel.getEngineNo());
            }
            profomaInvoiceNoText.setText("");
        }

    }
}
