/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.view;

import com.incosyz.sms.config.Setting;
import com.incosyz.sms.dialog.CashSalesReport;
import com.incosyz.sms.mixmodel.GETOrderModel;
import com.incosyz.sms.mixmodel.StockModel;
import com.incosyz.sms.model.BikeModel;
import com.incosyz.sms.model.CustomerModel;
import com.incosyz.sms.model.HomePhoneModel;
import com.incosyz.sms.model.MobileModel;
import com.incosyz.sms.model.OrderModel;
import com.incosyz.sms.report.ReportGenerator;
import java.awt.Container;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 * Date : Nov 24, 2015 Time : 3:21:11 PM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class LeasingSaleReport extends javax.swing.JFrame {

    static JasperReport leasingSale_report;

    public static String REPORT_PATH = "./src/com/incosyz/sms/report/";

    /**
     * Creates new form DailySalesReport
     */
    public LeasingSaleReport() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            if (leasingSale_report == null) {
                leasingSale_report = JasperCompileManager.compileReport(REPORT_PATH + "DailySalesReportLeasingSales.jrxml");
            }
        } catch (JRException ex) {
            Logger.getLogger(LeasingSaleReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();
        homeText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        provinceText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        datePurchaseText = new javax.swing.JTextField();
        roundNoText = new javax.swing.JTextField();
        modelColorText = new javax.swing.JTextField();
        poNoText = new javax.swing.JTextField();
        profomaInvoiceNoText = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        reportNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        poValueText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        chequeText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        poNoPText = new javax.swing.JTextField();
        downPaymentText = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        engineNoText = new javax.swing.JTextField();
        dateReport = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sales Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 230, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Leasing Sales");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 10, 350, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Name Mr, Mrs :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 100, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Payment Details :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 170, 210, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Mobile No :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 170, 100, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 170, 100, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Home / Office :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 110, 100, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("NIC No :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 230, 100, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Province :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 230, 100, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Date of Purchase :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 290, 110, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Round No :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 410, 110, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Remark :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(440, 420, 210, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Profoma Invoice No");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(210, 470, 110, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Po No");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 470, 110, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Model / Color :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(210, 410, 110, 20);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Customer Details :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 80, 210, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Samagi Traders - Leasing Sales Report ");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(30, 10, 350, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/printReport.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 550, 110, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/viewReport.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(650, 550, 110, 50);
        jPanel1.add(nameText);
        nameText.setBounds(30, 130, 150, 30);
        jPanel1.add(homeText);
        homeText.setBounds(210, 130, 150, 30);
        jPanel1.add(addressText);
        addressText.setBounds(210, 190, 150, 30);
        jPanel1.add(mobileText);
        mobileText.setBounds(30, 190, 150, 30);
        jPanel1.add(provinceText);
        provinceText.setBounds(30, 250, 150, 30);
        jPanel1.add(nicText);
        nicText.setBounds(210, 250, 150, 30);
        jPanel1.add(datePurchaseText);
        datePurchaseText.setBounds(30, 310, 150, 30);
        jPanel1.add(roundNoText);
        roundNoText.setBounds(30, 430, 150, 30);
        jPanel1.add(modelColorText);
        modelColorText.setBounds(210, 430, 150, 30);
        jPanel1.add(poNoText);
        poNoText.setBounds(30, 490, 150, 30);
        jPanel1.add(profomaInvoiceNoText);
        profomaInvoiceNoText.setBounds(210, 490, 150, 30);
        jPanel1.add(jTextField18);
        jTextField18.setBounds(440, 440, 320, 30);
        jPanel1.add(jTextField19);
        jTextField19.setBounds(440, 470, 320, 30);
        jPanel1.add(jTextField20);
        jTextField20.setBounds(440, 500, 320, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Report No :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(440, 100, 100, 20);
        jPanel1.add(reportNo);
        reportNo.setBounds(440, 120, 150, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Report Date :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(610, 100, 100, 20);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("PO Value :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(610, 210, 100, 20);
        jPanel1.add(poValueText);
        poValueText.setBounds(610, 230, 150, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Amount :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(440, 330, 100, 20);
        jPanel1.add(amountText);
        amountText.setBounds(440, 350, 150, 30);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Cheque/Cash :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(610, 270, 100, 20);
        jPanel1.add(chequeText);
        chequeText.setBounds(610, 290, 150, 30);
        jPanel1.add(dateText);
        dateText.setBounds(610, 350, 150, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Date :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(610, 330, 110, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Motor Bike Details :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 380, 210, 20);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("PO NO :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(440, 210, 100, 20);
        jPanel1.add(poNoPText);
        poNoPText.setBounds(440, 230, 150, 30);
        jPanel1.add(downPaymentText);
        downPaymentText.setBounds(440, 290, 150, 30);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Down Payment");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(440, 270, 100, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Engine No :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 530, 110, 20);
        jPanel1.add(engineNoText);
        engineNoText.setBounds(30, 550, 150, 30);
        jPanel1.add(dateReport);
        dateReport.setBounds(610, 120, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = nameText.getText();
        String mobile = mobileText.getText();
        String home = homeText.getText();
        String address = addressText.getText();
        String province = provinceText.getText();
        String nic = nicText.getText();
        String pdate = datePurchaseText.getText();

        String roundNo = roundNoText.getText();
        String modelColor = modelColorText.getText();
        String engineNo = engineNoText.getText();
        String profomaInvoiceNo = profomaInvoiceNoText.getText();
        String poNo = poNoText.getText();

        String poNoP = poNoPText.getText();
        String poValue = poValueText.getText();
        String downPayment = downPaymentText.getText();
        String cheque = chequeText.getText();
        String amount = amountText.getText();
        String date = dateText.getText();

        String rNo = reportNo.getText();

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String rDate = dateFormat.format(dateReport.getDate());
        try {
            Map<String, Object> map = new HashMap<>();

            Setting s = new Setting();
            String companyName = s.getProperty("NAME");
            String code = s.getProperty("CODE");

            map.put("dealerName", companyName);
            map.put("dealerCode", code);
            map.put("date", rDate);
            map.put("reportNo", rNo);

            map.put("name", name);
            map.put("mobile", mobile);
            map.put("home", home);
            map.put("address", address);
            map.put("province", province);
            map.put("nic", nic);
            map.put("pdate", pdate);

            map.put("poNo", poNo);
            map.put("roundNo", roundNo);
            map.put("modelColor", modelColor);
            map.put("engineNo", engineNo);

            map.put("poNoP", poNoP);
            map.put("poNoValue", poValue);
            map.put("downPayment", downPayment);
            map.put("cheque", cheque);
            map.put("amount", amount);
            map.put("dateP", date);

            Container generateReport = ReportGenerator.generateReport(leasingSale_report, null, map, null);
            CashSalesReport cashSalesReport = new CashSalesReport(generateReport);
            cashSalesReport.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(CashSalesReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LeasingSaleReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = nameText.getText();
        String mobile = mobileText.getText();
        String home = homeText.getText();
        String address = addressText.getText();
        String province = provinceText.getText();
        String nic = nicText.getText();
        String pdate = datePurchaseText.getText();

        String roundNo = roundNoText.getText();
        String modelColor = modelColorText.getText();
        String engineNo = engineNoText.getText();
        String profomaInvoiceNo = profomaInvoiceNoText.getText();
        String poNo = poNoText.getText();

        String poNoP = poNoPText.getText();
        String poValue = poValueText.getText();
        String downPayment = downPaymentText.getText();
        String cheque = chequeText.getText();
        String amount = amountText.getText();
        String date = dateText.getText();

        String rNo = reportNo.getText();

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String rDate = dateFormat.format(dateReport.getDate());
        try {
            Map<String, Object> map = new HashMap<>();

            Setting s = new Setting();
            String companyName = s.getProperty("NAME");
            String code = s.getProperty("CODE");

            map.put("dealerName", companyName);
            map.put("dealerCode", code);
            map.put("date", rDate);
            map.put("reportNo", rNo);

            map.put("name", name);
            map.put("mobile", mobile);
            map.put("home", home);
            map.put("address", address);
            map.put("province", province);
            map.put("nic", nic);
            map.put("pdate", pdate);

            map.put("poNo", poNo);
            map.put("roundNo", roundNo);
            map.put("modelColor", modelColor);
            map.put("engineNo", engineNo);

            map.put("poNoP", poNoP);
            map.put("poNoValue", poValue);
            map.put("downPayment", downPayment);
            map.put("cheque", cheque);
            map.put("amount", amount);
            map.put("dateP", date);

            Container generateReport = ReportGenerator.generateReport(leasingSale_report, null, map, null);
            CashSalesReport cashSalesReport = new CashSalesReport(generateReport);
            cashSalesReport.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(CashSalesReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LeasingSaleReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeasingSaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeasingSaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeasingSaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeasingSaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeasingSaleReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField amountText;
    private javax.swing.JTextField chequeText;
    private javax.swing.JTextField datePurchaseText;
    private org.jdesktop.swingx.JXDatePicker dateReport;
    private javax.swing.JTextField dateText;
    private javax.swing.JTextField downPaymentText;
    private javax.swing.JTextField engineNoText;
    private javax.swing.JTextField homeText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField modelColorText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nicText;
    private javax.swing.JTextField poNoPText;
    private javax.swing.JTextField poNoText;
    private javax.swing.JTextField poValueText;
    private javax.swing.JTextField profomaInvoiceNoText;
    private javax.swing.JTextField provinceText;
    private javax.swing.JTextField reportNo;
    private javax.swing.JTextField roundNoText;
    // End of variables declaration//GEN-END:variables

    public void setDetail(GETOrderModel gETOrderModel) {
        CustomerModel customerModel = gETOrderModel.getCustomerModel();
        ArrayList<HomePhoneModel> homePhoneModel = gETOrderModel.getHomePhoneModels();
        ArrayList<MobileModel> mobileModels = gETOrderModel.getMobileModels();
        OrderModel orderModel = gETOrderModel.getOrderModel();
        BikeModel bikeModel = gETOrderModel.getBikeModel();
        StockModel stockModel = gETOrderModel.getStockModel();

        if (customerModel != null) {
            nameText.setText(customerModel.getCustomerName());

            if (homePhoneModel.size() > 0) {
                homeText.setText(homePhoneModel.get(0).getHomePhoneNo());
            }

            if (mobileModels.size() > 0) {
                mobileText.setText(mobileModels.get(0).getMobileNo());
            }

            addressText.setText(customerModel.getAddressLineOne() + ", " + customerModel.getAddressLineTwo() + ", " + customerModel.getAddressLineThree());
            provinceText.setText("");
            nicText.setText(customerModel.getNicNo());
            datePurchaseText.setText(orderModel.getOrderDate());

            roundNoText.setText(orderModel.getRoundNo());
            modelColorText.setText(stockModel.getColour());

            if (stockModel.getEngineNo().length() > 4) {
                poNoText.setText(stockModel.getEngineNo().substring(stockModel.getEngineNo().length() - 4, stockModel.getEngineNo().length()));
            } else {
                poNoText.setText(stockModel.getEngineNo());
            }
            profomaInvoiceNoText.setText("");
            engineNoText.setText(stockModel.getEngineNo());
        }

    }

}
