/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.view;

import com.incosyz.sms.clientcontroller.OrderControllerClient;
import com.incosyz.sms.clientcontroller.Validation;
import com.incosyz.sms.mixmodel.LeasingOrderModel;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stelan-PC
 */
public class ViewLeasingSale extends javax.swing.JFrame {

    private ArrayList<LeasingOrderModel> leasingOrderModels;

    /**
     * Creates new form ViewLeasingSale
     */
    public ViewLeasingSale() {
        initComponents();
        setLocationRelativeTo(null);

        leasingTableModel = (DefaultTableModel) leasingTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leasingTable = new javax.swing.JTable();
        toDatePicker = new org.jdesktop.swingx.JXDatePicker();
        fromDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        snCount = new javax.swing.JLabel();
        leasingCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Leasing Info");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        leasingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "roundNo ", "leasingName ", "leasingAmount ", "mta ", "mta2", "mta3 ", "do ", "do2 ", "idCopy ", "gs", "gap ", "idPhoto ", "garanter ", "snCharge "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        leasingTable.setRowHeight(25);
        jScrollPane1.setViewportView(leasingTable);
        if (leasingTable.getColumnModel().getColumnCount() > 0) {
            leasingTable.getColumnModel().getColumn(3).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(5).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(6).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(7).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(8).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(9).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(10).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(11).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(12).setPreferredWidth(20);
            leasingTable.getColumnModel().getColumn(13).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 860, 430);
        jPanel1.add(toDatePicker);
        toDatePicker.setBounds(290, 50, 190, 30);
        jPanel1.add(fromDatePicker);
        fromDatePicker.setBounds(20, 52, 190, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("To :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 20, 150, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("From :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 24, 150, 30);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 50, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Other Leasing Count :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 530, 230, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("SN Leasing Count :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 530, 230, 20);

        snCount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        snCount.setText("00");
        jPanel1.add(snCount);
        snCount.setBounds(20, 550, 230, 30);

        leasingCount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leasingCount.setText("00");
        jPanel1.add(leasingCount);
        leasingCount.setBounds(280, 550, 230, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Search :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(670, 30, 110, 20);

        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });
        jPanel1.add(searchText);
        searchText.setBounds(670, 50, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String fromDate = dateFormat.format(fromDatePicker.getDate());
        String toDate = dateFormat.format(toDatePicker.getDate());
        try {
            leasingOrderModels = OrderControllerClient.getLeasingOrder(fromDate, toDate);
            setData(leasingOrderModels);
        } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLeasingSale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        String text = searchText.getText();
        if (Validation.isNumber(text)) {
            searchRoundNo(text);
        } else {
            searchLeasing(text);
        }
    }//GEN-LAST:event_searchTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLeasingSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLeasingSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLeasingSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLeasingSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLeasingSale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker fromDatePicker;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leasingCount;
    private javax.swing.JTable leasingTable;
    private javax.swing.JTextField searchText;
    private javax.swing.JLabel snCount;
    private org.jdesktop.swingx.JXDatePicker toDatePicker;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel leasingTableModel;
    private int snCountText;
    private int otherCountText;

    public void searchRoundNo(String text) {
        ArrayList<LeasingOrderModel> models = new ArrayList<>();
        for (LeasingOrderModel leasingOrderModel : leasingOrderModels) {
            if (leasingOrderModel.getRoundNo().contains(text)) {
                models.add(leasingOrderModel);
            }
        }
        setData(models);
    }

    public void searchLeasing(String text) {
        ArrayList<LeasingOrderModel> models = new ArrayList<>();
        for (LeasingOrderModel leasingOrderModel : leasingOrderModels) {
            if (leasingOrderModel.getLeasingName().toLowerCase().contains(text.toLowerCase())) {
                models.add(leasingOrderModel);
            }
        }
        setData(models);
    }

    public void setData(ArrayList<LeasingOrderModel> leasingOrderModels) {
        leasingTableModel.setRowCount(0);
        snCountText = 0;
        otherCountText = 0;
        for (LeasingOrderModel leasingOrderModel : leasingOrderModels) {
            setRow(leasingOrderModel);
        }
        snCount.setText(String.valueOf(snCountText));
        leasingCount.setText(String.valueOf(otherCountText));
    }

    public void setRow(LeasingOrderModel leasingOrderModel) {
        try {
            if (leasingOrderModel != null) {

                String mta = "";
                if (leasingOrderModel.getMta().equals("1")) {
                    mta = "OK";
                }

                String mta2 = "";
                if (leasingOrderModel.getMta2().equals("1")) {
                    mta2 = "OK";
                }

                String mta3 = "";
                if (leasingOrderModel.getMta3().equals("1")) {
                    mta3 = "OK";
                }

                String do1 = "";
                if (leasingOrderModel.getDo1().equals("1")) {
                    do1 = "OK";
                }

                String do2 = "";
                if (leasingOrderModel.getDo2().equals("1")) {
                    do2 = "OK";
                }

                String idCopy = "";
                if (leasingOrderModel.getIdCopy().equals("1")) {
                    idCopy = "OK";
                }

                String gs = "";
                if (leasingOrderModel.getGs().equals("1")) {
                    gs = "OK";
                }

                String gap = "";
                if (leasingOrderModel.getGap().equals("1")) {
                    gap = "OK";
                }

                String idPhoto = "";
                if (leasingOrderModel.getIdPhoto().equals("1")) {
                    idPhoto = "OK";
                }

                Object[] objects = {
                    leasingOrderModel.getRoundNo(),
                    leasingOrderModel.getLeasingName(),
                    leasingOrderModel.getLeasingAmount(),
                    mta,
                    mta2,
                    mta3,
                    do1,
                    do2,
                    idCopy,
                    gs,
                    gap,
                    idPhoto,
                    leasingOrderModel.getGaranter(),
                    leasingOrderModel.getSnCharge()
                };

                if (leasingOrderModel.getLeasingName().equals("SN Leasing")) {
                    snCountText++;
                } else {
                    otherCountText++;
                }

                leasingTableModel.addRow(objects);
            }
        } catch (Exception E) {

        }
    }
}
