/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.view;

import com.incosyz.sms.clientcontroller.SaleControllerImplClient;
import com.incosyz.sms.dialog.CashPayment;
import com.incosyz.sms.dialog.EditSale;
import com.incosyz.sms.mixmodel.GETOrderModel;
import com.incosyz.sms.mixmodel.StockModel;
import com.incosyz.sms.model.BikeModel;
import com.incosyz.sms.model.CashModel;
import com.incosyz.sms.model.CheckModel;
import com.incosyz.sms.model.CustomerModel;
import com.incosyz.sms.model.HomePhoneModel;
import com.incosyz.sms.model.LeasingModel;
import com.incosyz.sms.model.MobileModel;
import com.incosyz.sms.model.Model;
import com.incosyz.sms.model.NoteTableModel;
import com.incosyz.sms.model.OrderModel;
import com.incosyz.sms.model.PaymentModel;
import com.incosyz.sms.model.UserModel;
import com.incosyz.sms.other.CurrancyFormat;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 * Date : Nov 18, 2015 Time : 10:30:05 AM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class ViewOrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrderDetail
     */
    public ViewOrderDetail() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        roundNoText = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        modelNameText = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        chassisNoText = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        engineNoText = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        colourText = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        optionText = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        sellingPriceText = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        customerNameText = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        nicNoText = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        addressThree = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        mobileFourText = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        addressOne = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        add2 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        homePhoneThreeText = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        homePhoneOneText = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        homePhoneTwoText = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        mobileOneText = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        mobileTwoText = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        mobileThreeText = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        orderAmountText = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        rmvAmountText = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        insuranceAmountText = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        bikeAmountText = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tvsAmountText = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        commisionText = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        otherAmountText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        cashAmountText = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        chequeAmountText = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel49 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        leasingText = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        totalPaidText = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        haveToPaidText = new javax.swing.JLabel();
        haveToSettleButton = new javax.swing.JButton();
        jPanel62 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        leasingText1 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        snChargeText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteTextIs = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Samagi Traders - Sale Management");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 350, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sales Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 230, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bike Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel3.setLayout(null);

        jPanel19.setBackground(new java.awt.Color(244, 244, 244));
        jPanel19.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Round No  :");
        jPanel19.add(jLabel19);
        jLabel19.setBounds(10, 0, 80, 30);

        jPanel3.add(jPanel19);
        jPanel19.setBounds(20, 40, 100, 30);

        jPanel21.setBackground(new java.awt.Color(250, 250, 250));
        jPanel21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(null);

        roundNoText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        roundNoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundNoText.setText("2002/22");
        jPanel21.add(roundNoText);
        roundNoText.setBounds(10, 0, 110, 30);

        jPanel3.add(jPanel21);
        jPanel21.setBounds(120, 40, 120, 30);

        jPanel22.setBackground(new java.awt.Color(250, 250, 250));
        jPanel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(null);

        modelNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modelNameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        modelNameText.setText("2002/22");
        jPanel22.add(modelNameText);
        modelNameText.setBounds(10, 0, 190, 30);

        jPanel3.add(jPanel22);
        jPanel22.setBounds(20, 110, 220, 30);

        jPanel23.setBackground(new java.awt.Color(244, 244, 244));
        jPanel23.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Model Name  :");
        jPanel23.add(jLabel23);
        jLabel23.setBounds(10, 0, 210, 30);

        jPanel3.add(jPanel23);
        jPanel23.setBounds(20, 80, 220, 30);

        jPanel24.setBackground(new java.awt.Color(250, 250, 250));
        jPanel24.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(null);

        chassisNoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chassisNoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chassisNoText.setText("2002/22");
        jPanel24.add(chassisNoText);
        chassisNoText.setBounds(10, 0, 190, 30);

        jPanel3.add(jPanel24);
        jPanel24.setBounds(20, 170, 220, 30);

        jPanel25.setBackground(new java.awt.Color(244, 244, 244));
        jPanel25.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Chassis No  :");
        jPanel25.add(jLabel25);
        jLabel25.setBounds(10, 0, 210, 30);

        jPanel3.add(jPanel25);
        jPanel25.setBounds(20, 140, 220, 30);

        jPanel26.setBackground(new java.awt.Color(250, 250, 250));
        jPanel26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(null);

        engineNoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        engineNoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        engineNoText.setText("2002/22");
        jPanel26.add(engineNoText);
        engineNoText.setBounds(10, 0, 190, 30);

        jPanel3.add(jPanel26);
        jPanel26.setBounds(20, 230, 220, 30);

        jPanel27.setBackground(new java.awt.Color(244, 244, 244));
        jPanel27.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Engine No  :");
        jPanel27.add(jLabel27);
        jLabel27.setBounds(10, 0, 210, 30);

        jPanel3.add(jPanel27);
        jPanel27.setBounds(20, 200, 220, 30);

        jPanel28.setBackground(new java.awt.Color(250, 250, 250));
        jPanel28.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.setLayout(null);

        colourText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        colourText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        colourText.setText("2002/22");
        jPanel28.add(colourText);
        colourText.setBounds(10, 0, 120, 30);

        jPanel3.add(jPanel28);
        jPanel28.setBounds(100, 270, 140, 30);

        jPanel29.setBackground(new java.awt.Color(244, 244, 244));
        jPanel29.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Colour  :");
        jPanel29.add(jLabel29);
        jLabel29.setBounds(10, 0, 70, 30);

        jPanel3.add(jPanel29);
        jPanel29.setBounds(20, 270, 80, 30);

        jPanel30.setBackground(new java.awt.Color(250, 250, 250));
        jPanel30.setForeground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(null);

        optionText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        optionText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        optionText.setText("2002/22");
        jPanel30.add(optionText);
        optionText.setBounds(10, 0, 120, 30);

        jPanel3.add(jPanel30);
        jPanel30.setBounds(100, 310, 140, 30);

        jPanel31.setBackground(new java.awt.Color(244, 244, 244));
        jPanel31.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Option  :");
        jPanel31.add(jLabel31);
        jLabel31.setBounds(10, 0, 70, 30);

        jPanel3.add(jPanel31);
        jPanel31.setBounds(20, 310, 80, 30);

        jPanel32.setBackground(new java.awt.Color(244, 244, 244));
        jPanel32.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Selling Price");
        jPanel32.add(jLabel32);
        jLabel32.setBounds(10, 0, 210, 30);

        jPanel3.add(jPanel32);
        jPanel32.setBounds(20, 350, 220, 30);

        jPanel33.setBackground(new java.awt.Color(250, 250, 250));
        jPanel33.setForeground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(null);

        sellingPriceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sellingPriceText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sellingPriceText.setText("Rs 0.00");
        jPanel33.add(sellingPriceText);
        sellingPriceText.setBounds(10, 0, 190, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/change.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel33.add(jButton2);
        jButton2.setBounds(190, 0, 30, 30);

        jPanel3.add(jPanel33);
        jPanel33.setBounds(20, 380, 220, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 80, 260, 430);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel13.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(244, 244, 244));
        jPanel15.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Customer Name :");
        jPanel15.add(jLabel13);
        jLabel13.setBounds(10, 0, 210, 30);

        jPanel13.add(jPanel15);
        jPanel15.setBounds(20, 40, 220, 30);

        jPanel16.setBackground(new java.awt.Color(244, 244, 244));
        jPanel16.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Round No");
        jPanel16.add(jLabel15);
        jLabel15.setBounds(20, 0, 210, 20);

        jPanel13.add(jPanel16);
        jPanel16.setBounds(20, 40, 220, 20);

        jPanel17.setBackground(new java.awt.Color(250, 250, 250));
        jPanel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        customerNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerNameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel17.add(customerNameText);
        customerNameText.setBounds(10, 0, 190, 30);

        jPanel13.add(jPanel17);
        jPanel17.setBounds(20, 70, 220, 30);

        jPanel18.setBackground(new java.awt.Color(250, 250, 250));
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(null);

        nicNoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nicNoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel18.add(nicNoText);
        nicNoText.setBounds(10, 0, 200, 30);

        jPanel13.add(jPanel18);
        jPanel18.setBounds(20, 130, 220, 30);

        jPanel37.setBackground(new java.awt.Color(244, 244, 244));
        jPanel37.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("NIC Number :");
        jPanel37.add(jLabel18);
        jLabel18.setBounds(10, 0, 210, 30);

        jPanel13.add(jPanel37);
        jPanel37.setBounds(20, 100, 220, 30);

        jPanel38.setBackground(new java.awt.Color(250, 250, 250));
        jPanel38.setForeground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(null);

        addressThree.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressThree.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel38.add(addressThree);
        addressThree.setBounds(10, 0, 190, 20);

        jPanel13.add(jPanel38);
        jPanel38.setBounds(20, 230, 220, 20);

        jPanel39.setBackground(new java.awt.Color(244, 244, 244));
        jPanel39.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Address");
        jPanel39.add(jLabel38);
        jLabel38.setBounds(10, 0, 210, 30);

        jPanel13.add(jPanel39);
        jPanel39.setBounds(20, 160, 220, 30);

        jPanel40.setBackground(new java.awt.Color(250, 250, 250));
        jPanel40.setForeground(new java.awt.Color(255, 255, 255));
        jPanel40.setLayout(null);

        mobileFourText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mobileFourText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel40.add(mobileFourText);
        mobileFourText.setBounds(10, 0, 190, 0);

        jPanel13.add(jPanel40);
        jPanel40.setBounds(20, 350, 220, 20);

        jPanel41.setBackground(new java.awt.Color(244, 244, 244));
        jPanel41.setLayout(null);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Mobile No :");
        jPanel41.add(jLabel40);
        jLabel40.setBounds(10, 0, 210, 30);

        jPanel13.add(jPanel41);
        jPanel41.setBounds(20, 260, 220, 30);

        jPanel42.setBackground(new java.awt.Color(244, 244, 244));
        jPanel42.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Home / Office No :");
        jPanel42.add(jLabel41);
        jLabel41.setBounds(10, 0, 210, 30);

        jPanel13.add(jPanel42);
        jPanel42.setBounds(20, 390, 220, 30);

        jPanel43.setBackground(new java.awt.Color(250, 250, 250));
        jPanel43.setForeground(new java.awt.Color(255, 255, 255));
        jPanel43.setLayout(null);

        addressOne.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressOne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel43.add(addressOne);
        addressOne.setBounds(10, 0, 190, 20);

        jPanel13.add(jPanel43);
        jPanel43.setBounds(20, 190, 220, 20);

        jPanel44.setBackground(new java.awt.Color(250, 250, 250));
        jPanel44.setForeground(new java.awt.Color(255, 255, 255));
        jPanel44.setLayout(null);

        add2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel44.add(add2);
        add2.setBounds(10, 0, 190, 20);

        jPanel13.add(jPanel44);
        jPanel44.setBounds(20, 210, 220, 20);

        jPanel45.setBackground(new java.awt.Color(250, 250, 250));
        jPanel45.setForeground(new java.awt.Color(255, 255, 255));
        jPanel45.setLayout(null);

        homePhoneThreeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homePhoneThreeText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel45.add(homePhoneThreeText);
        homePhoneThreeText.setBounds(10, 0, 190, 20);

        jPanel13.add(jPanel45);
        jPanel45.setBounds(20, 460, 220, 20);

        jPanel50.setBackground(new java.awt.Color(250, 250, 250));
        jPanel50.setForeground(new java.awt.Color(255, 255, 255));
        jPanel50.setLayout(null);

        homePhoneOneText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homePhoneOneText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel50.add(homePhoneOneText);
        homePhoneOneText.setBounds(10, 0, 190, 20);

        jPanel13.add(jPanel50);
        jPanel50.setBounds(20, 420, 220, 20);

        jPanel51.setBackground(new java.awt.Color(250, 250, 250));
        jPanel51.setForeground(new java.awt.Color(255, 255, 255));
        jPanel51.setLayout(null);

        homePhoneTwoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homePhoneTwoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel51.add(homePhoneTwoText);
        homePhoneTwoText.setBounds(10, 0, 190, 20);

        jPanel13.add(jPanel51);
        jPanel51.setBounds(20, 440, 220, 20);

        jPanel52.setBackground(new java.awt.Color(250, 250, 250));
        jPanel52.setForeground(new java.awt.Color(255, 255, 255));
        jPanel52.setLayout(null);

        mobileOneText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mobileOneText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel52.add(mobileOneText);
        mobileOneText.setBounds(10, 0, 190, 0);

        jPanel13.add(jPanel52);
        jPanel52.setBounds(20, 290, 220, 20);

        jPanel53.setBackground(new java.awt.Color(250, 250, 250));
        jPanel53.setForeground(new java.awt.Color(255, 255, 255));
        jPanel53.setLayout(null);

        mobileTwoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mobileTwoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel53.add(mobileTwoText);
        mobileTwoText.setBounds(10, 0, 190, 0);

        jPanel13.add(jPanel53);
        jPanel53.setBounds(20, 310, 220, 20);

        jPanel54.setBackground(new java.awt.Color(250, 250, 250));
        jPanel54.setForeground(new java.awt.Color(255, 255, 255));
        jPanel54.setLayout(null);

        mobileThreeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mobileThreeText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel54.add(mobileThreeText);
        mobileThreeText.setBounds(10, 0, 190, 0);

        jPanel13.add(jPanel54);
        jPanel54.setBounds(20, 330, 220, 20);

        jPanel1.add(jPanel13);
        jPanel13.setBounds(300, 80, 260, 490);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel5.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(255, 204, 153));
        jPanel11.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Order Amount :");
        jPanel11.add(jLabel5);
        jLabel5.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel11);
        jPanel11.setBounds(20, 300, 130, 30);

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(null);

        orderAmountText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        orderAmountText.setText("Rs 0.00");
        jPanel12.add(orderAmountText);
        orderAmountText.setBounds(10, 0, 160, 30);

        jPanel5.add(jPanel12);
        jPanel12.setBounds(150, 300, 180, 30);

        jPanel14.setBackground(new java.awt.Color(244, 244, 244));
        jPanel14.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("RMV Amount :");
        jPanel14.add(jLabel12);
        jLabel12.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel14);
        jPanel14.setBounds(20, 200, 130, 30);

        jPanel20.setBackground(new java.awt.Color(250, 250, 250));
        jPanel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(null);

        rmvAmountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rmvAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rmvAmountText.setText("Rs 0.00");
        jPanel20.add(rmvAmountText);
        rmvAmountText.setBounds(10, 0, 160, 30);

        jPanel5.add(jPanel20);
        jPanel20.setBounds(150, 200, 180, 30);

        jPanel34.setBackground(new java.awt.Color(244, 244, 244));
        jPanel34.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Insurance :");
        jPanel34.add(jLabel20);
        jLabel20.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel34);
        jPanel34.setBounds(20, 230, 130, 30);

        jPanel35.setBackground(new java.awt.Color(250, 250, 250));
        jPanel35.setForeground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(null);

        insuranceAmountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        insuranceAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        insuranceAmountText.setText("Rs 0.00");
        jPanel35.add(insuranceAmountText);
        insuranceAmountText.setBounds(10, 0, 160, 30);

        jPanel5.add(jPanel35);
        jPanel35.setBounds(150, 230, 180, 30);

        jPanel56.setBackground(new java.awt.Color(244, 244, 244));
        jPanel56.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Bike Amount :");
        jPanel56.add(jLabel24);
        jLabel24.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel56);
        jPanel56.setBounds(20, 170, 130, 30);

        jPanel57.setBackground(new java.awt.Color(250, 250, 250));
        jPanel57.setForeground(new java.awt.Color(255, 255, 255));
        jPanel57.setLayout(null);

        bikeAmountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bikeAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bikeAmountText.setText("Rs 0.00");
        jPanel57.add(bikeAmountText);
        bikeAmountText.setBounds(10, 0, 160, 30);

        jPanel5.add(jPanel57);
        jPanel57.setBounds(150, 170, 180, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Tvs Amount :");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(20, 30, 110, 20);

        tvsAmountText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tvsAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tvsAmountText.setText("Rs 0.00");
        jPanel5.add(tvsAmountText);
        tvsAmountText.setBounds(140, 30, 160, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Commision :");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(20, 50, 110, 20);

        commisionText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        commisionText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        commisionText.setText("Rs 0.00");
        jPanel5.add(commisionText);
        commisionText.setBounds(140, 50, 160, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Other Amount :");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(20, 70, 110, 20);

        otherAmountText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        otherAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        otherAmountText.setText("Rs 0.00");
        jPanel5.add(otherAmountText);
        otherAmountText.setBounds(140, 70, 160, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Note  :");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(20, 100, 110, 20);

        jPanel36.setBackground(new java.awt.Color(244, 244, 244));
        jPanel36.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Cash Paid :");
        jPanel36.add(jLabel26);
        jLabel26.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel36);
        jPanel36.setBounds(20, 340, 130, 30);

        jPanel46.setBackground(new java.awt.Color(250, 250, 250));
        jPanel46.setForeground(new java.awt.Color(255, 255, 255));
        jPanel46.setLayout(null);

        cashAmountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cashAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cashAmountText.setText("Rs 0.00");
        jPanel46.add(cashAmountText);
        cashAmountText.setBounds(10, 0, 140, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/change.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel46.add(jButton4);
        jButton4.setBounds(150, 0, 30, 30);

        jPanel5.add(jPanel46);
        jPanel46.setBounds(150, 340, 180, 30);

        jPanel47.setBackground(new java.awt.Color(244, 244, 244));
        jPanel47.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Cheque Paid :");
        jPanel47.add(jLabel28);
        jLabel28.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel47);
        jPanel47.setBounds(20, 370, 130, 30);

        jPanel48.setBackground(new java.awt.Color(250, 250, 250));
        jPanel48.setForeground(new java.awt.Color(255, 255, 255));
        jPanel48.setLayout(null);

        chequeAmountText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        chequeAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chequeAmountText.setText("Rs 0.00");
        jPanel48.add(chequeAmountText);
        chequeAmountText.setBounds(10, 0, 140, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/change.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel48.add(jButton5);
        jButton5.setBounds(150, 0, 30, 30);

        jPanel5.add(jPanel48);
        jPanel48.setBounds(150, 370, 180, 30);

        jPanel49.setBackground(new java.awt.Color(244, 244, 244));
        jPanel49.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Leasing :");
        jPanel49.add(jLabel30);
        jLabel30.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel49);
        jPanel49.setBounds(20, 400, 130, 30);

        jPanel55.setBackground(new java.awt.Color(250, 250, 250));
        jPanel55.setForeground(new java.awt.Color(255, 255, 255));
        jPanel55.setLayout(null);

        leasingText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        leasingText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leasingText.setText("Rs 0.00");
        jPanel55.add(leasingText);
        leasingText.setBounds(10, 0, 140, 30);

        jPanel5.add(jPanel55);
        jPanel55.setBounds(150, 400, 180, 30);

        jPanel58.setBackground(new java.awt.Color(255, 204, 153));
        jPanel58.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Total Paid :");
        jPanel58.add(jLabel6);
        jLabel6.setBounds(10, 0, 110, 40);

        jPanel5.add(jPanel58);
        jPanel58.setBounds(20, 440, 130, 40);

        jPanel59.setBackground(new java.awt.Color(255, 255, 204));
        jPanel59.setForeground(new java.awt.Color(255, 255, 255));
        jPanel59.setLayout(null);

        totalPaidText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalPaidText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPaidText.setText("Rs 0.00");
        jPanel59.add(totalPaidText);
        totalPaidText.setBounds(10, 0, 160, 40);

        jPanel5.add(jPanel59);
        jPanel59.setBounds(150, 440, 180, 40);

        jPanel60.setBackground(new java.awt.Color(244, 244, 244));
        jPanel60.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Have To Settle :");
        jPanel60.add(jLabel33);
        jLabel33.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel60);
        jPanel60.setBounds(20, 480, 130, 30);

        jPanel61.setBackground(new java.awt.Color(250, 250, 250));
        jPanel61.setForeground(new java.awt.Color(255, 255, 255));
        jPanel61.setLayout(null);

        haveToPaidText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        haveToPaidText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        haveToPaidText.setText("Rs 0.00");
        jPanel61.add(haveToPaidText);
        haveToPaidText.setBounds(10, 0, 140, 30);

        haveToSettleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/change.jpg"))); // NOI18N
        haveToSettleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haveToSettleButtonActionPerformed(evt);
            }
        });
        jPanel61.add(haveToSettleButton);
        haveToSettleButton.setBounds(150, 0, 30, 30);

        jPanel5.add(jPanel61);
        jPanel61.setBounds(150, 480, 180, 30);

        jPanel62.setBackground(new java.awt.Color(244, 244, 244));
        jPanel62.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Leasing :");
        jPanel62.add(jLabel34);
        jLabel34.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel62);
        jPanel62.setBounds(20, 400, 130, 30);

        jPanel63.setBackground(new java.awt.Color(250, 250, 250));
        jPanel63.setForeground(new java.awt.Color(255, 255, 255));
        jPanel63.setLayout(null);

        leasingText1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        leasingText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leasingText1.setText("Rs 0.00");
        jPanel63.add(leasingText1);
        leasingText1.setBounds(10, 0, 140, 30);

        jPanel5.add(jPanel63);
        jPanel63.setBounds(150, 400, 180, 30);

        jPanel64.setBackground(new java.awt.Color(244, 244, 244));
        jPanel64.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("SN Charges :");
        jPanel64.add(jLabel35);
        jLabel35.setBounds(10, 0, 110, 30);

        jPanel5.add(jPanel64);
        jPanel64.setBounds(20, 260, 130, 30);

        jPanel65.setBackground(new java.awt.Color(250, 250, 250));
        jPanel65.setForeground(new java.awt.Color(255, 255, 255));
        jPanel65.setLayout(null);

        snChargeText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        snChargeText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        snChargeText.setText("Rs 0.00");
        jPanel65.add(snChargeText);
        snChargeText.setBounds(10, 0, 160, 30);

        jPanel5.add(jPanel65);
        jPanel65.setBounds(150, 260, 180, 30);

        noteTextIs.setEditable(false);
        noteTextIs.setColumns(20);
        noteTextIs.setRows(5);
        jScrollPane2.setViewportView(noteTextIs);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(70, 100, 260, 60);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(570, 50, 350, 520);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(null);

        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(username);
        username.setBounds(30, 0, 890, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 570, 950, 40);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        noteText.setEditable(false);
        noteText.setColumns(20);
        noteText.setRows(5);
        noteText.setBorder(null);
        jScrollPane1.setViewportView(noteText);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 520, 220, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void haveToSettleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haveToSettleButtonActionPerformed
        EditSale editSale = new EditSale(this, true);
        editSale.setFrame(bigWindow);
        editSale.setOrder(gETOrderModel);
        editSale.setVisible(true);
    }//GEN-LAST:event_haveToSettleButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CashPayment cashPayment = new CashPayment(this, true);
        cashPayment.setCash(gETOrderModel.getCashModels());
        cashPayment.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ManageCheque cheque = new ManageCheque(gETOrderModel.getPaymentModel().getPaymentId());
        cheque.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add2;
    private javax.swing.JLabel addressOne;
    private javax.swing.JLabel addressThree;
    private javax.swing.JLabel bikeAmountText;
    private javax.swing.JLabel cashAmountText;
    private javax.swing.JLabel chassisNoText;
    private javax.swing.JLabel chequeAmountText;
    private javax.swing.JLabel colourText;
    private javax.swing.JLabel commisionText;
    private javax.swing.JLabel customerNameText;
    private javax.swing.JLabel engineNoText;
    private javax.swing.JLabel haveToPaidText;
    private javax.swing.JButton haveToSettleButton;
    private javax.swing.JLabel homePhoneOneText;
    private javax.swing.JLabel homePhoneThreeText;
    private javax.swing.JLabel homePhoneTwoText;
    private javax.swing.JLabel insuranceAmountText;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel leasingText;
    private javax.swing.JLabel leasingText1;
    private javax.swing.JLabel mobileFourText;
    private javax.swing.JLabel mobileOneText;
    private javax.swing.JLabel mobileThreeText;
    private javax.swing.JLabel mobileTwoText;
    private javax.swing.JLabel modelNameText;
    private javax.swing.JLabel nicNoText;
    private javax.swing.JTextArea noteText;
    private javax.swing.JTextArea noteTextIs;
    private javax.swing.JLabel optionText;
    private javax.swing.JLabel orderAmountText;
    private javax.swing.JLabel otherAmountText;
    private javax.swing.JLabel rmvAmountText;
    private javax.swing.JLabel roundNoText;
    private javax.swing.JLabel sellingPriceText;
    private javax.swing.JLabel snChargeText;
    private javax.swing.JLabel totalPaidText;
    private javax.swing.JLabel tvsAmountText;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    private ViewSaleBigWindow bigWindow;
    private GETOrderModel gETOrderModel;

    public void setFrame(ViewSaleBigWindow bigWindow) {
        this.bigWindow = bigWindow;
    }

    public void setNote(String orderId) {
        try {
            NoteTableModel infoNoteTable = SaleControllerImplClient.getInfoNoteTable(orderId);
            System.out.println("AWWWWWWWWWWWWWWW : " + infoNoteTable);
            if (infoNoteTable != null) {
                noteTextIs.setText(infoNoteTable.getNote());
            }            
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ViewOrderDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setDetail(GETOrderModel gETOrderModel) {
        this.gETOrderModel = gETOrderModel;
        OrderModel orderModel = gETOrderModel.getOrderModel();
        Model model = gETOrderModel.getModel();
        BikeModel bikeModel = gETOrderModel.getBikeModel();
        StockModel stockModel = gETOrderModel.getStockModel();
        CustomerModel customerModel = gETOrderModel.getCustomerModel();
        PaymentModel paymentModel = gETOrderModel.getPaymentModel();
        UserModel userModel = gETOrderModel.getUserModel();

        if (userModel != null) {
            String bottom = "Order created by : " + userModel.getUserName()
                    + " @ " + orderModel.getOrderTime() + " - " + orderModel.getOrderDate();
            username.setText(bottom);

        }

        ArrayList<CashModel> cashModels = gETOrderModel.getCashModels();
        ArrayList<CheckModel> checkModels = gETOrderModel.getCheckModels();
        LeasingModel leasingModel = gETOrderModel.getLeasingModel();

        ArrayList<MobileModel> mobileModels = gETOrderModel.getMobileModels();
        ArrayList<HomePhoneModel> homePhoneModels = gETOrderModel.getHomePhoneModels();

        if (orderModel != null) {
            roundNoText.setText(orderModel.getRoundNo());
            System.out.println(orderModel.getOrderId());
            setNote(orderModel.getOrderId());
            modelNameText.setText(model.getModelName());
            chassisNoText.setText(stockModel.getChassisNo());
            engineNoText.setText(stockModel.getEngineNo());
            colourText.setText(stockModel.getColour());

            double amount = Double.parseDouble(orderModel.getOrderAmount());
            if (leasingModel != null) {
                amount += Double.parseDouble(leasingModel.getSnCharge());
            }

            orderAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(amount));

        }

        if (bikeModel != null) {
            optionText.setText(bikeModel.getBikeOption());
            sellingPriceText.setText("Rs " + CurrancyFormat.getCurrancyFormat(bikeModel.getNetAmount()));
        }

        if (customerModel != null) {
            customerNameText.setText(customerModel.getCustomerName());
            nicNoText.setText(customerModel.getNicNo());
            addressOne.setText(customerModel.getAddressLineOne());
            add2.setText(customerModel.getAddressLineTwo());
            addressThree.setText(customerModel.getAddressLineThree());
        }

        if (paymentModel != null) {
            tvsAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(paymentModel.getBikeAmount()));
            commisionText.setText("Rs " + CurrancyFormat.getCurrancyFormat(paymentModel.getCommision()));

            double tvsAmount = 0;
            if (paymentModel.getOtherPaymentAmount() != null) {
                otherAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(paymentModel.getOtherPaymentAmount()));
                tvsAmount = Double.parseDouble(paymentModel.getBikeAmount()) - Double.parseDouble(paymentModel.getCommision()) - Double.parseDouble(paymentModel.getOtherPaymentAmount());
            } else {
                otherAmountText.setText("Rs 0.00");
                tvsAmount = Double.parseDouble(paymentModel.getBikeAmount()) - Double.parseDouble(paymentModel.getCommision());
            }

            noteText.setText(paymentModel.getNote());

            System.out.println(tvsAmount + "  S");
            tvsAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(tvsAmount));

            bikeAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(paymentModel.getBikeAmount()));
            rmvAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(paymentModel.getRmvAmount()));
            insuranceAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(paymentModel.getInsuranceAmount()));
        }

        double cash = 0;
        if (cashModels != null) {

            for (CashModel cashModel : cashModels) {
                cash += Double.parseDouble(cashModel.getCashAmount());
            }
            cashAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(cash));

        }

        double cheque = 0;
        if (checkModels != null) {

            for (CheckModel checkModel : checkModels) {
                cheque += Double.parseDouble(checkModel.getAmount());
            }
            chequeAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(cheque));
        }
        double amount = 0;
        if (leasingModel != null) {
            amount = Double.parseDouble(leasingModel.getLeasingAmount());
            leasingText.setText("Rs " + CurrancyFormat.getCurrancyFormat(amount));
        }

        double totalPaid = cash + cheque + amount;
        totalPaidText.setText("Rs " + CurrancyFormat.getCurrancyFormat(totalPaid));

        double orderAmount = Double.parseDouble(orderModel.getOrderAmount());
        if (leasingModel != null) {
            String snCharge = leasingModel.getSnCharge();
            snChargeText.setText("Rs " + CurrancyFormat.getCurrancyFormat(snCharge));
            orderAmount += Double.parseDouble(snCharge);
        }

        haveToPaidText.setText("Rs " + CurrancyFormat.getCurrancyFormat(orderAmount - totalPaid));
        if (orderAmount - totalPaid == 0) {
            haveToSettleButton.setEnabled(false);
        }

        if (homePhoneModels != null) {

            JLabel[] hFields = {homePhoneOneText, homePhoneTwoText, homePhoneThreeText};

            for (int i = 0; i < homePhoneModels.size(); i++) {
                hFields[i].setText(homePhoneModels.get(i).getHomePhoneNo());
            }
        }

        if (mobileModels != null) {

            JLabel[] fields = {mobileOneText, mobileTwoText, mobileThreeText, mobileFourText};
            int j = mobileModels.size() > 4 ? 4 : mobileModels.size();
            for (int i = 0; i < j; i++) {
                fields[i].setText(mobileModels.get(i).getMobileNo());
            }

        }

    }

}
