/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.dialog;

import com.incosyz.sms.mixmodel.DealerPrices;
import com.incosyz.sms.other.Validation;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Date : Nov 3, 2015 Time : 10:10:16 AM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class ChangeFullTotal extends javax.swing.JDialog {

    /**
     * Creates new form ChangeFullTotal
     */
    public ChangeFullTotal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        remittanceLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        remittanceText = new javax.swing.JTextField();
        bikeAmountText = new javax.swing.JTextField();
        commisionText = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bikeAmountLabel = new javax.swing.JLabel();
        commisionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        commisionLabel1 = new javax.swing.JLabel();
        otherPaymentText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        commisionLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Model Amount");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 20, 320, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Sales Management System -> Create New Sale -> Manage Sale");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 50, 440, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Net remittance :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 390, 170, 30);

        remittanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        remittanceLabel.setForeground(new java.awt.Color(153, 153, 153));
        remittanceLabel.setText("213,650.00");
        jPanel1.add(remittanceLabel);
        remittanceLabel.setBounds(50, 410, 170, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("All Inclusive Reail Price :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 100, 170, 30);

        remittanceText.setEditable(false);
        remittanceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        remittanceText.setText("213,650.00");
        remittanceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remittanceTextActionPerformed(evt);
            }
        });
        jPanel1.add(remittanceText);
        remittanceText.setBounds(240, 390, 180, 30);

        bikeAmountText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bikeAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikeAmountTextActionPerformed(evt);
            }
        });
        bikeAmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bikeAmountTextKeyReleased(evt);
            }
        });
        jPanel1.add(bikeAmountText);
        bikeAmountText.setBounds(240, 100, 180, 30);

        commisionText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        commisionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commisionTextActionPerformed(evt);
            }
        });
        commisionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                commisionTextKeyReleased(evt);
            }
        });
        jPanel1.add(commisionText);
        commisionText.setBounds(240, 160, 180, 30);

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/done.jpg"))); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doneButton);
        doneButton.setBounds(310, 460, 110, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/cancel.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 460, 110, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Commision :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 160, 170, 30);

        bikeAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bikeAmountLabel.setForeground(new java.awt.Color(153, 153, 153));
        bikeAmountLabel.setText("217,900.00");
        jPanel1.add(bikeAmountLabel);
        bikeAmountLabel.setBounds(50, 120, 170, 30);

        commisionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        commisionLabel.setForeground(new java.awt.Color(153, 153, 153));
        commisionLabel.setText("4,250.00");
        jPanel1.add(commisionLabel);
        commisionLabel.setBounds(50, 180, 170, 30);

        noteText.setColumns(20);
        noteText.setRows(5);
        jScrollPane1.setViewportView(noteText);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 280, 180, 96);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Note :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 280, 170, 30);

        commisionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        commisionLabel1.setForeground(new java.awt.Color(153, 153, 153));
        commisionLabel1.setText("write simple note");
        jPanel1.add(commisionLabel1);
        commisionLabel1.setBounds(50, 300, 170, 30);

        otherPaymentText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        otherPaymentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherPaymentTextActionPerformed(evt);
            }
        });
        otherPaymentText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                otherPaymentTextKeyReleased(evt);
            }
        });
        jPanel1.add(otherPaymentText);
        otherPaymentText.setBounds(240, 220, 180, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Other payment :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 220, 170, 30);

        commisionLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        commisionLabel2.setForeground(new java.awt.Color(153, 153, 153));
        commisionLabel2.setText("###");
        jPanel1.add(commisionLabel2);
        commisionLabel2.setBounds(50, 240, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remittanceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remittanceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remittanceTextActionPerformed

    private void bikeAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikeAmountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bikeAmountTextActionPerformed

    private void commisionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commisionTextActionPerformed

    }//GEN-LAST:event_commisionTextActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed

        String bikeAmount = bikeAmountText.getText();
        String commision = commisionText.getText();
        String otherPayment = otherPaymentText.getText();
        String remittance = remittanceText.getText();

        if (otherPayment.equals("")) {
            otherPaymentText.setText("0.00");
        }
        if (commisionText.equals("")) {
            commisionText.setText("0.00");
        }

        Validation v = new Validation();
        boolean inputCurrancy = v.checkNumberForCurrency(bikeAmount);
        boolean inputCurrancy1 = v.checkNumberForCurrency(commision);
        boolean inputCurrancy2 = v.checkNumberForCurrency(otherPayment);

        if (inputCurrancy && inputCurrancy1 && inputCurrancy2) {

            boolean countinue = true;
            String message = "";
            if (Double.parseDouble(commisionText.getText()) < 0) {
                countinue = false;
                message += "Commision ,";
            }
            if (Double.parseDouble(bikeAmountText.getText()) < 0) {
                countinue = false;
                message += "Inclusive price ,";
            }
            if (Double.parseDouble(otherPaymentText.getText()) < 0) {
                countinue = false;
                message += "Other payments ,";
            }
            if (message.length() > 3) {
                message = message.substring(0, message.length() - 1) + " wrong format. check inputs again. can't be use minus values !";
            }
            if (countinue) {
                dealerPrices.setBikeAmount(bikeAmount);
                dealerPrices.setCommision(commision);
                dealerPrices.setOtherPayment(otherPayment);
                dealerPrices.setNetRemittance(remittance);
                dealerPrices.setValueNote(noteText.getText());
                manageSaleDetail.setDealerPrices(dealerPrices);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, message);
            }

        } else {

            JOptionPane.showMessageDialog(this, "Input data is not valid. check again !");
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void otherPaymentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherPaymentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherPaymentTextActionPerformed


    private void commisionTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commisionTextKeyReleased
        try {
            otherPaymentText.setText(String.format("%1.2f", getOtherpayment()));
            otherPaymentText.setForeground(Color.BLACK);
            Validation v = new Validation();
            v.inputCurrancy(commisionText);
        } catch (NumberFormatException e) {
            Validation v = new Validation();
            v.inputCurrancy(commisionText);
        }
    }//GEN-LAST:event_commisionTextKeyReleased

    private void otherPaymentTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherPaymentTextKeyReleased
        try {
            commisionText.setText(String.format("%1.2f", getCommision()));
            commisionText.setForeground(Color.BLACK);
            Validation v = new Validation();
            v.inputCurrancy(otherPaymentText);
        } catch (NumberFormatException e) {
            Validation v = new Validation();
            v.inputCurrancy(otherPaymentText);
        }
    }//GEN-LAST:event_otherPaymentTextKeyReleased

    private void bikeAmountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bikeAmountTextKeyReleased
        try {
            commisionText.setText(String.format("%1.2f", getCommision()));
            commisionText.setForeground(Color.BLACK);
            Validation v = new Validation();
            v.inputCurrancy(bikeAmountText);
        } catch (NumberFormatException e) {
            Validation v = new Validation();
            v.inputCurrancy(bikeAmountText);
        }
    }//GEN-LAST:event_bikeAmountTextKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeFullTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeFullTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeFullTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeFullTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeFullTotal dialog = new ChangeFullTotal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bikeAmountLabel;
    private javax.swing.JTextField bikeAmountText;
    private javax.swing.JLabel commisionLabel;
    private javax.swing.JLabel commisionLabel1;
    private javax.swing.JLabel commisionLabel2;
    private javax.swing.JTextField commisionText;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noteText;
    private javax.swing.JTextField otherPaymentText;
    private javax.swing.JLabel remittanceLabel;
    private javax.swing.JTextField remittanceText;
    // End of variables declaration//GEN-END:variables

    private DealerPrices dealerPrices;
    private ManageSaleDetail manageSaleDetail;

    public void setFrame(ManageSaleDetail manageSaleDetail) {
        this.manageSaleDetail = manageSaleDetail;
    }

    public void setDetail(DealerPrices dealerPrices) {
        this.dealerPrices = dealerPrices;

        bikeAmountText.setText(String.format("%1.2f", Double.parseDouble(dealerPrices.getBikeAmount())));
//        bikeAmount = Double.parseDouble(dealerPrices.getBikeAmount());
        commisionText.setText(String.format("%1.2f", Double.parseDouble(dealerPrices.getCommision())));
//        commision = Double.parseDouble(dealerPrices.getCommision());
        remittanceText.setText(String.format("%1.2f", Double.parseDouble(dealerPrices.getNetRemittance())));

        String otherPayment = dealerPrices.getOtherPayment() ;

        if (otherPayment != null) {
            otherPaymentText.setText(String.format("%1.2f", Double.parseDouble(dealerPrices.getOtherPayment())));
        }else{
            otherPaymentText.setText("0.00");
        }
        
        String note = dealerPrices.getValueNote();
        if (note != null) {
            noteText.setText(note);
        }else{
            noteText.setText("");
        }
        
        
        bikeAmountLabel.setText(dealerPrices.getBikeAmount());
        commisionLabel.setText(dealerPrices.getCommision());
        remittanceLabel.setText(dealerPrices.getNetRemittance());
    }

    public double getCommision() {
        double bikeAmount = 0;
        if (!bikeAmountText.getText().trim().equals("")) {
            bikeAmount = Double.parseDouble(bikeAmountText.getText());
        }
        double otherPayment = 0;
        if (!otherPaymentText.getText().trim().equals("")) {
            otherPayment = Double.parseDouble(otherPaymentText.getText());
        }

        double netRemittance = 0;
        if (!remittanceText.getText().trim().equals("")) {
            netRemittance = Double.parseDouble(remittanceText.getText());
        }

        return bikeAmount - otherPayment - netRemittance;
    }

    public double getOtherpayment() {
        double bikeAmount = 0;
        if (!bikeAmountText.getText().trim().equals("")) {
            bikeAmount = Double.parseDouble(bikeAmountText.getText());
        }
        double commision = 0;
        if (!commisionText.getText().trim().equals("")) {
            commision = Double.parseDouble(commisionText.getText());
        }

        double netRemittance = 0;
        if (!remittanceText.getText().trim().equals("")) {
            netRemittance = Double.parseDouble(remittanceText.getText());
        }

        return bikeAmount - commision - netRemittance;
    }
}
