/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.dialog;

import com.incosyz.sms.clientcontroller.DeliveryNoteControllerClient;
import com.incosyz.sms.clientcontroller.Generator;
import com.incosyz.sms.model.BatchModel;
import com.incosyz.sms.other.Validation;
import com.incosyz.sms.view.ManageDeliveryOrder;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Date : Oct 27, 2015 Time : 7:35:54 PM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class DeliveryNoteDetail extends javax.swing.JDialog {

    private BatchModel batchModel;
    private boolean updateMode = false;

    /**
     * Creates new form SpecialConsignment
     */
    public DeliveryNoteDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setUpdateMode(BatchModel batchModel) {
        this.batchModel = batchModel;
        updateMode = true;

        consignmentNoteNoText.setText(batchModel.getConsignmentNoteNo());
        orderRequestNoText.setText(batchModel.getOrderRequestNo());
        transportOrderNoText.setText(batchModel.getTransportOrderNo());
        transportInvoiceNoText.setText(batchModel.getTransportInvoiceNo());
        userIdText.setText(batchModel.getUserId());
        manualText.setText(batchModel.getManual());
        warrantyManualText.setText(batchModel.getWarrantyManual());
        toolKitText.setText(batchModel.getToolKit());
        jacketText.setText(batchModel.getJacket());
        sideMirrorText.setText(batchModel.getSideMirror());
        helmetText.setText(batchModel.getHelmet());
        vehicleNoText.setText(batchModel.getVehicleNo());
        driverNameText.setText(batchModel.getDriverName());
        helperNameText.setText(batchModel.getHelperName());
        contactNoText.setText(batchModel.getContactNo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        orderRequestNoText = new javax.swing.JTextField();
        consignmentNoteNoText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        transportOrderNoText = new javax.swing.JTextField();
        transportInvoiceNoText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        userIdText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        manualText = new javax.swing.JTextField();
        toolKitText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sideMirrorText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        warrantyManualText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jacketText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        helmetText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        vehicleNoText = new javax.swing.JTextField();
        driverNameText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        helperNameText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        contactNoText = new javax.swing.JTextField();
        batchDate = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Samagi Traders - Create New Delivery Note");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 550, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sales Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 230, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Date :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 90, 200, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Order Request No :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 160, 200, 30);

        orderRequestNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderRequestNoTextActionPerformed(evt);
            }
        });
        jPanel1.add(orderRequestNoText);
        orderRequestNoText.setBounds(30, 190, 210, 30);

        consignmentNoteNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consignmentNoteNoTextActionPerformed(evt);
            }
        });
        jPanel1.add(consignmentNoteNoText);
        consignmentNoteNoText.setBounds(30, 260, 210, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Consignment Note No :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 230, 200, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Transport Order No :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 300, 200, 30);

        transportOrderNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportOrderNoTextActionPerformed(evt);
            }
        });
        transportOrderNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                transportOrderNoTextKeyReleased(evt);
            }
        });
        jPanel1.add(transportOrderNoText);
        transportOrderNoText.setBounds(30, 330, 210, 30);

        transportInvoiceNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportInvoiceNoTextActionPerformed(evt);
            }
        });
        jPanel1.add(transportInvoiceNoText);
        transportInvoiceNoText.setBounds(30, 400, 210, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Transport Invoice No :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 370, 200, 30);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/done.jpg"))); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);
        addButton.setBounds(660, 460, 110, 50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("User ID :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 440, 200, 30);

        userIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdTextActionPerformed(evt);
            }
        });
        jPanel1.add(userIdText);
        userIdText.setBounds(30, 470, 210, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Manual :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(280, 90, 110, 30);

        manualText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualTextActionPerformed(evt);
            }
        });
        manualText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                manualTextKeyReleased(evt);
            }
        });
        jPanel1.add(manualText);
        manualText.setBounds(280, 120, 110, 30);

        toolKitText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolKitTextActionPerformed(evt);
            }
        });
        toolKitText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toolKitTextKeyReleased(evt);
            }
        });
        jPanel1.add(toolKitText);
        toolKitText.setBounds(280, 190, 110, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tool Kits :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(280, 160, 110, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Side Mirrors :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(280, 230, 110, 30);

        sideMirrorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideMirrorTextActionPerformed(evt);
            }
        });
        sideMirrorText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sideMirrorTextKeyReleased(evt);
            }
        });
        jPanel1.add(sideMirrorText);
        sideMirrorText.setBounds(280, 260, 110, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Warranty :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(410, 90, 110, 30);

        warrantyManualText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrantyManualTextActionPerformed(evt);
            }
        });
        warrantyManualText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                warrantyManualTextKeyReleased(evt);
            }
        });
        jPanel1.add(warrantyManualText);
        warrantyManualText.setBounds(410, 120, 110, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Jackets :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(410, 160, 110, 30);

        jacketText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacketTextActionPerformed(evt);
            }
        });
        jacketText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jacketTextKeyReleased(evt);
            }
        });
        jPanel1.add(jacketText);
        jacketText.setBounds(410, 190, 110, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Helmets :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(410, 230, 110, 30);

        helmetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helmetTextActionPerformed(evt);
            }
        });
        helmetText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                helmetTextKeyReleased(evt);
            }
        });
        jPanel1.add(helmetText);
        helmetText.setBounds(410, 260, 110, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Vehicle No :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(560, 90, 200, 30);

        vehicleNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoTextActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleNoText);
        vehicleNoText.setBounds(560, 120, 210, 30);

        driverNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(driverNameText);
        driverNameText.setBounds(560, 190, 210, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Driver Name :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(560, 160, 200, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Helper Name :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(560, 230, 200, 30);

        helperNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helperNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(helperNameText);
        helperNameText.setBounds(560, 260, 210, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Contact No :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(560, 300, 200, 30);

        contactNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoTextActionPerformed(evt);
            }
        });
        contactNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNoTextKeyReleased(evt);
            }
        });
        jPanel1.add(contactNoText);
        contactNoText.setBounds(560, 330, 210, 30);

        batchDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batchDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchDateActionPerformed(evt);
            }
        });
        jPanel1.add(batchDate);
        batchDate.setBounds(30, 120, 210, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/cancel.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(543, 460, 110, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/clear.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 460, 110, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/d.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean canAdd = true;

        String consignmentNoteNo = consignmentNoteNoText.getText();
        if (consignmentNoteNo.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Consignment Note no cannot be empty !");
            canAdd = false;
        }

        if (canAdd) {

            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String batchId = "";
            String dateText = dateFormat.format(batchDate.getDate());
            String orderRequestNo = orderRequestNoText.getText();
            String transportOrderNo = transportOrderNoText.getText();
            String transportInvoiceNo = transportInvoiceNoText.getText();
            String userId = userIdText.getText();
            String manual = manualText.getText();
            String toolKit = toolKitText.getText();
            String sideMirror = sideMirrorText.getText();
            String warranty = warrantyManualText.getText();
            String jacket = jacketText.getText();
            String helmet = helmetText.getText();
            String vehicleNo = vehicleNoText.getText();
            String driver = driverNameText.getText();
            String helper = helperNameText.getText();
            String contact = contactNoText.getText();

            if (manual.trim().equals("")) {
                manual = "0";
            }

            if (toolKit.trim().equals("")) {
                toolKit = "0";
            }

            if (sideMirror.trim().equals("")) {
                sideMirror = "0";
            }

            if (warranty.trim().equals("")) {
                warranty = "0";
            }

            if (jacket.trim().equals("")) {
                jacket = "0";
            }

            if (helmet.trim().equals("")) {
                helmet = "0";
            }

            BatchModel batchModel = new BatchModel()
                    .setBatchDate(dateText)
                    .setOrderRequestNo(orderRequestNo)
                    .setConsignmentNoteNo(consignmentNoteNo)
                    .setTransportOrderNo(transportOrderNo)
                    .setTransportInvoiceNo(transportInvoiceNo)
                    .setUserId(userId)
                    .setManual(manual)
                    .setToolKit(toolKit)
                    .setSideMirror(sideMirror)
                    .setWarrantyManual(warranty)
                    .setJacket(jacket)
                    .setHelmet(helmet)
                    .setDriverName(driver)
                    .setHelperName(helper)
                    .setContactNo(contact)
                    .setVehicleNo(vehicleNo);

            if (updateMode) {
                batchModel.setBatchId(this.batchModel.getBatchId());
                try {
                    boolean updateDeliveryNote = DeliveryNoteControllerClient.updateDeliveryNote(batchModel);
                    if (updateDeliveryNote) {
                        manageDeliveryOrder.refresh();
                        JOptionPane.showMessageDialog(this, "Updated successfully !");
                    } else {
                        JOptionPane.showMessageDialog(this, "Updated failed !");
                    }
                } catch (NotBoundException | MalformedURLException | ClassNotFoundException | RemoteException | SQLException ex) {
                    Logger.getLogger(DeliveryNoteDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    batchId = Generator.generateId("Batch", "BatchId", "B", 3);
                    batchModel.setBatchId(batchId);
                    boolean addDeliveryNote = DeliveryNoteControllerClient.addDeliveryNote(batchModel);
                    if (addDeliveryNote) {
                        manageDeliveryOrder.addToArrayList(batchModel);
                        JOptionPane.showMessageDialog(this, "Batch added successfully !");
                        dispose();
                        ManageDeliveryOrderDetail manageDeliveryOrderDetail = new ManageDeliveryOrderDetail(manageDeliveryOrder, true);
                        manageDeliveryOrderDetail.setParentFrame(batchModel, manageDeliveryOrder.getAllBatch());
                        manageDeliveryOrderDetail.setVisible(true);
                    }
                } catch (NotBoundException | MalformedURLException | ClassNotFoundException | RemoteException | SQLException ex) {
                    Logger.getLogger(DeliveryNoteDetail.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void transportOrderNoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transportOrderNoTextKeyReleased

    }//GEN-LAST:event_transportOrderNoTextKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manualTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manualTextKeyReleased
        Validation v = new Validation();
        v.validateNumber(manualText);
    }//GEN-LAST:event_manualTextKeyReleased

    private void warrantyManualTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_warrantyManualTextKeyReleased
        Validation v = new Validation();
        v.validateNumber(warrantyManualText);
    }//GEN-LAST:event_warrantyManualTextKeyReleased

    private void toolKitTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toolKitTextKeyReleased
        Validation v = new Validation();
        v.validateNumber(toolKitText);
    }//GEN-LAST:event_toolKitTextKeyReleased

    private void jacketTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jacketTextKeyReleased
        Validation v = new Validation();
        v.validateNumber(jacketText);
    }//GEN-LAST:event_jacketTextKeyReleased

    private void helmetTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_helmetTextKeyReleased
        Validation v = new Validation();
        v.validateNumber(helmetText);
    }//GEN-LAST:event_helmetTextKeyReleased

    private void sideMirrorTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sideMirrorTextKeyReleased
        Validation v = new Validation();
        v.validateNumber(sideMirrorText);
    }//GEN-LAST:event_sideMirrorTextKeyReleased

    private void contactNoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoTextKeyReleased
        Validation v = new Validation();
        v.validateContactNo(contactNoText);
    }//GEN-LAST:event_contactNoTextKeyReleased

    private void orderRequestNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderRequestNoTextActionPerformed
        consignmentNoteNoText.requestFocus();
    }//GEN-LAST:event_orderRequestNoTextActionPerformed

    private void consignmentNoteNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consignmentNoteNoTextActionPerformed
        transportOrderNoText.requestFocus();
    }//GEN-LAST:event_consignmentNoteNoTextActionPerformed

    private void transportOrderNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportOrderNoTextActionPerformed
        transportInvoiceNoText.requestFocus();
    }//GEN-LAST:event_transportOrderNoTextActionPerformed

    private void transportInvoiceNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportInvoiceNoTextActionPerformed
        userIdText.requestFocus();
    }//GEN-LAST:event_transportInvoiceNoTextActionPerformed

    private void batchDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchDateActionPerformed
        orderRequestNoText.requestFocus();
    }//GEN-LAST:event_batchDateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        orderRequestNoText.setText("");
        consignmentNoteNoText.setText("");
        transportOrderNoText.setText("");
        transportInvoiceNoText.setText("");
        userIdText.setText("");
        manualText.setText("");
        warrantyManualText.setText("");
        toolKitText.setText("");
        jacketText.setText("");
        sideMirrorText.setText("");
        helmetText.setText("");
        vehicleNoText.setText("");
        driverNameText.setText("");
        helperNameText.setText("");
        contactNoText.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdTextActionPerformed
        manualText.requestFocus();
    }//GEN-LAST:event_userIdTextActionPerformed

    private void manualTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualTextActionPerformed
        toolKitText.requestFocus();
    }//GEN-LAST:event_manualTextActionPerformed

    private void toolKitTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolKitTextActionPerformed
        sideMirrorText.requestFocus();
    }//GEN-LAST:event_toolKitTextActionPerformed

    private void sideMirrorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideMirrorTextActionPerformed
        warrantyManualText.requestFocus();
    }//GEN-LAST:event_sideMirrorTextActionPerformed

    private void warrantyManualTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrantyManualTextActionPerformed
        jacketText.requestFocus();
    }//GEN-LAST:event_warrantyManualTextActionPerformed

    private void jacketTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacketTextActionPerformed
        helmetText.requestFocus();
    }//GEN-LAST:event_jacketTextActionPerformed

    private void helmetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helmetTextActionPerformed
        vehicleNoText.requestFocus();
    }//GEN-LAST:event_helmetTextActionPerformed

    private void vehicleNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoTextActionPerformed
        driverNameText.requestFocus();
    }//GEN-LAST:event_vehicleNoTextActionPerformed

    private void driverNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverNameTextActionPerformed
        helperNameText.requestFocus();
    }//GEN-LAST:event_driverNameTextActionPerformed

    private void helperNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helperNameTextActionPerformed
        contactNoText.requestFocus();
    }//GEN-LAST:event_helperNameTextActionPerformed

    private void contactNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoTextActionPerformed
        addButton.doClick();
    }//GEN-LAST:event_contactNoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeliveryNoteDetail dialog = new DeliveryNoteDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private org.jdesktop.swingx.JXDatePicker batchDate;
    private javax.swing.JTextField consignmentNoteNoText;
    private javax.swing.JTextField contactNoText;
    private javax.swing.JTextField driverNameText;
    private javax.swing.JTextField helmetText;
    private javax.swing.JTextField helperNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jacketText;
    private javax.swing.JTextField manualText;
    private javax.swing.JTextField orderRequestNoText;
    private javax.swing.JTextField sideMirrorText;
    private javax.swing.JTextField toolKitText;
    private javax.swing.JTextField transportInvoiceNoText;
    private javax.swing.JTextField transportOrderNoText;
    private javax.swing.JTextField userIdText;
    private javax.swing.JTextField vehicleNoText;
    private javax.swing.JTextField warrantyManualText;
    // End of variables declaration//GEN-END:variables
    private ManageDeliveryOrder manageDeliveryOrder;

    public void setParentFrame(ManageDeliveryOrder manageDeliveryOrder) {
        this.manageDeliveryOrder = manageDeliveryOrder;
    }
}
