/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.dialog;

import com.incosyz.sms.clientcontroller.CustomerControllerImplClient;
import com.incosyz.sms.clientcontroller.Generator;
import com.incosyz.sms.clientcontroller.OrderControllerClient;
import com.incosyz.sms.clientcontroller.SaleControllerImplClient;
import com.incosyz.sms.mixmodel.GETOrderModel;
import com.incosyz.sms.model.CashModel;
import com.incosyz.sms.model.CheckModel;
import com.incosyz.sms.model.LeasingModel;
import com.incosyz.sms.model.OrderModel;
import com.incosyz.sms.model.PaymentModel;
import com.incosyz.sms.other.CurrancyFormat;
import com.incosyz.sms.other.Validation;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Date : Nov 30, 2015 Time : 8:55:37 PM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class LeasingPayment extends javax.swing.JDialog {

    /**
     * Creates new form LeasingPayment
     */
    public LeasingPayment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        leasingPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paidAmountText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        balanceAmountText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        leasingAmountText = new javax.swing.JTextField();
        snLeasingPanel = new javax.swing.JPanel();
        doCheck1 = new javax.swing.JCheckBox();
        mta2Check = new javax.swing.JCheckBox();
        mtaCheck = new javax.swing.JCheckBox();
        gsCheck = new javax.swing.JCheckBox();
        gapCheck = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        garanerDetail = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        doneButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        snChargeText = new javax.swing.JTextField();
        leasingPanel = new javax.swing.JPanel();
        mta3Check1 = new javax.swing.JCheckBox();
        do2Check = new javax.swing.JCheckBox();
        idCopyCheck1 = new javax.swing.JCheckBox();
        idPhotose2 = new javax.swing.JCheckBox();
        leasignCombo1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sales Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 280, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Samagi Traders - Leasing Payment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 400, 25);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Paid Amount :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 140, 190, 20);

        paidAmountText.setEditable(false);
        jPanel1.add(paidAmountText);
        paidAmountText.setBounds(40, 160, 220, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Balance :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 210, 190, 20);

        balanceAmountText.setEditable(false);
        jPanel1.add(balanceAmountText);
        balanceAmountText.setBounds(40, 230, 220, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("SN Chargers :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 280, 190, 20);

        leasingAmountText.setEditable(false);
        jPanel1.add(leasingAmountText);
        leasingAmountText.setBounds(40, 370, 220, 30);

        snLeasingPanel.setBackground(new java.awt.Color(255, 255, 255));
        snLeasingPanel.setLayout(null);

        doCheck1.setBackground(new java.awt.Color(255, 255, 255));
        doCheck1.setText("  DO");
        snLeasingPanel.add(doCheck1);
        doCheck1.setBounds(20, 90, 110, 23);

        mta2Check.setBackground(new java.awt.Color(255, 255, 255));
        mta2Check.setText("  MTA3");
        snLeasingPanel.add(mta2Check);
        mta2Check.setBounds(20, 60, 110, 23);

        mtaCheck.setBackground(new java.awt.Color(255, 255, 255));
        mtaCheck.setText("  MTA2");
        snLeasingPanel.add(mtaCheck);
        mtaCheck.setBounds(20, 30, 110, 23);

        gsCheck.setBackground(new java.awt.Color(255, 255, 255));
        gsCheck.setText("  GS");
        snLeasingPanel.add(gsCheck);
        gsCheck.setBounds(160, 30, 110, 23);

        gapCheck.setBackground(new java.awt.Color(255, 255, 255));
        gapCheck.setText("  GAP");
        snLeasingPanel.add(gapCheck);
        gapCheck.setBounds(160, 60, 110, 23);

        garanerDetail.setColumns(20);
        garanerDetail.setRows(5);
        jScrollPane3.setViewportView(garanerDetail);

        snLeasingPanel.add(jScrollPane3);
        jScrollPane3.setBounds(20, 170, 380, 90);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Garanter Detail :");
        snLeasingPanel.add(jLabel17);
        jLabel17.setBounds(20, 140, 160, 30);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("  ID Photose");
        snLeasingPanel.add(jCheckBox1);
        jCheckBox1.setBounds(160, 90, 110, 23);

        jPanel1.add(snLeasingPanel);
        snLeasingPanel.setBounds(320, 120, 400, 270);

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/done.jpg"))); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doneButton);
        doneButton.setBounds(610, 410, 110, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Leasing Amount");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 350, 120, 20);

        snChargeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snChargeTextKeyReleased(evt);
            }
        });
        jPanel1.add(snChargeText);
        snChargeText.setBounds(40, 300, 220, 30);

        leasingPanel.setBackground(new java.awt.Color(255, 255, 255));
        leasingPanel.setLayout(null);

        mta3Check1.setBackground(new java.awt.Color(255, 255, 255));
        mta3Check1.setText("  MTA3");
        mta3Check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mta3Check1ActionPerformed(evt);
            }
        });
        leasingPanel.add(mta3Check1);
        mta3Check1.setBounds(0, 10, 81, 23);

        do2Check.setBackground(new java.awt.Color(255, 255, 255));
        do2Check.setText("  DO");
        leasingPanel.add(do2Check);
        do2Check.setBounds(0, 30, 81, 23);

        idCopyCheck1.setBackground(new java.awt.Color(255, 255, 255));
        idCopyCheck1.setText("  ID Copy");
        leasingPanel.add(idCopyCheck1);
        idCopyCheck1.setBounds(100, 10, 81, 23);

        idPhotose2.setBackground(new java.awt.Color(255, 255, 255));
        idPhotose2.setText("  ID Photose");
        leasingPanel.add(idPhotose2);
        idPhotose2.setBounds(100, 33, 170, 20);

        jPanel1.add(leasingPanel);
        leasingPanel.setBounds(340, 140, 190, 70);

        leasignCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SN Leasing", "Other Leasing" }));
        leasignCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leasignCombo1ActionPerformed(evt);
            }
        });
        jPanel1.add(leasignCombo1);
        leasignCombo1.setBounds(340, 90, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        OrderModel orderModel = gETOrderModel.getOrderModel();
        try {

            String mta = mtaCheck.isSelected() ? "1" : "0";
            String mta2 = mta2Check.isSelected() ? "1" : "0";
            String mta3 = mta3Check1.isSelected() ? "1" : "0";
            String doNo = doCheck1.isSelected() ? "1" : "0";
            String doNo2 = do2Check.isSelected() ? "1" : "0";
            String gs = gsCheck.isSelected() ? "1" : "0";
            String gap = gapCheck.isSelected() ? "1" : "0";
            String idPhotose;
            String idCopy2 = idCopyCheck1.isSelected() ? "1" : "0";

            if (!leasignCombo1.getSelectedItem().equals("SN Leasing")) {
                idPhotose = idPhotose2.isSelected() ? "1" : "0";
            } else {
                idPhotose = jCheckBox1.isSelected() ? "1" : "0";
            }
            String snCharge = snChargeText.getText();
            if (snCharge == null || snCharge.equals("")) {
                snCharge = "0";
            }

            String leasingAmount = String.valueOf(leasingAmountA);
            String garanter = garanerDetail.getText();
            String leasingName = (String) leasignCombo1.getSelectedItem();

            LeasingModel leasingModel = new LeasingModel()
                    .setPaymentId(orderModel.getPaymentId())
                    .setLeasingAmount(leasingAmount)
                    .setMta(mta)
                    .setMta2(mta2)
                    .setMta3(mta3)
                    .setDoNo(doNo)
                    .setDoNo2(doNo2)
                    .setIdCopy(idCopy2)
                    .setGs(gs)
                    .setGap(gap)
                    .setGaranter(garanter)
                    .setLeasingName(leasingName)
                    .setIdPhoto(idPhotose)
                    .setSnCharge(snCharge);

            boolean leasingExists = OrderControllerClient.leasingExists(orderModel.getPaymentId());
            if (leasingExists) {
                System.out.println(leasingExists);
                String leasingId1 = gETOrderModel.getLeasingModel().getLeasingId();
                leasingModel.setLeasingId(leasingId1);
                boolean updateLeasing = CustomerControllerImplClient.updateLeasing(leasingModel);
                if (updateLeasing) {
                    JOptionPane.showMessageDialog(this, "Leasing detail updated !");
                }
            } else {
                String leasingId = Generator.generateId("Leasing", "leasingId", "L", 3);
                leasingModel.setLeasingId(leasingId);
                boolean addLeasing = CustomerControllerImplClient.addLeasing(leasingModel);
                if (addLeasing) {
                    JOptionPane.showMessageDialog(this, "Leasing added successfully !");
                    dispose();
                }
            }
        } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LeasingPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void mta3Check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mta3Check1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mta3Check1ActionPerformed

    private void leasignCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leasignCombo1ActionPerformed
        String leasignName = (String) leasignCombo1.getSelectedItem();
        if (leasignName.equals("SN Leasing")) {
            snLeasingPanel.setVisible(true);
            leasingPanel.setVisible(false);
        } else {
            leasingPanel.setVisible(true);
            snLeasingPanel.setVisible(false);
        }
    }//GEN-LAST:event_leasignCombo1ActionPerformed

    private void snChargeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snChargeTextKeyReleased
        Validation v = new Validation();
        v.validateNumber(snChargeText);

        try {
            String snCharge = snChargeText.getText();
            snChargeA = Double.parseDouble(snChargeText.getText());
            leasingAmountA = snChargeA + balanceA;
            leasingAmountText.setText(CurrancyFormat.getCurrancyFormat(leasingAmountA));
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_snChargeTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeasingPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeasingPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeasingPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeasingPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LeasingPayment dialog = new LeasingPayment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceAmountText;
    private javax.swing.JCheckBox do2Check;
    private javax.swing.JCheckBox doCheck1;
    private javax.swing.JButton doneButton;
    private javax.swing.JCheckBox gapCheck;
    private javax.swing.JTextArea garanerDetail;
    private javax.swing.JCheckBox gsCheck;
    private javax.swing.JCheckBox idCopyCheck1;
    private javax.swing.JCheckBox idPhotose2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox leasignCombo1;
    private javax.swing.JTextField leasingAmountText;
    private javax.swing.JPanel leasingPanel;
    private javax.swing.JCheckBox mta2Check;
    private javax.swing.JCheckBox mta3Check1;
    private javax.swing.JCheckBox mtaCheck;
    private javax.swing.JTextField paidAmountText;
    private javax.swing.JTextField snChargeText;
    private javax.swing.JPanel snLeasingPanel;
    // End of variables declaration//GEN-END:variables

    double balanceA;
    double leasingAmountA;
    double snChargeA;

    private GETOrderModel gETOrderModel;

    public void setDetail(GETOrderModel gETOrderModel) {
        this.gETOrderModel = gETOrderModel;

        LeasingModel leasingModel = gETOrderModel.getLeasingModel();
        if (leasingModel != null) {
            String mta = leasingModel.getMta();
            if (mta.equals("1")) {
                mtaCheck.setSelected(true);
            } else {
                mtaCheck.setSelected(false);
            }

            String mta2 = leasingModel.getMta2();
            if (mta2.equals("1")) {
                mta2Check.setSelected(true);
            } else {
                mta2Check.setSelected(false);
            }

            String mta3 = leasingModel.getMta3();
            if (mta3.equals("1")) {
                mta3Check1.setSelected(true);
            } else {
                mta3Check1.setSelected(false);
            }

            String doNo = leasingModel.getDoNo();
            if (doNo.equals("1")) {
                doCheck1.setSelected(true);
            } else {
                doCheck1.setSelected(false);
            }

            String doNo2 = leasingModel.getDoNo2();
            if (doNo2.equals("1")) {
                do2Check.setSelected(true);
            } else {
                do2Check.setSelected(false);
            }

            String gs = leasingModel.getGs();
            if (gs.equals("1")) {
                gsCheck.setSelected(true);
            } else {
                gsCheck.setSelected(false);
            }

            String gap = leasingModel.getGap();
            if (gap.equals("1")) {
                gapCheck.setSelected(true);
            } else {
                gapCheck.setSelected(false);
            }

            String idCopy = leasingModel.getIdCopy();
            if (idCopy.equals("1")) {
                idCopyCheck1.setSelected(true);
            } else {
                idCopyCheck1.setSelected(false);
            }

            String idPhoto = leasingModel.getIdPhoto();
            if (idPhoto.equals("1")) {
                jCheckBox1.setSelected(true);
                idPhotose2.setSelected(true);
            } else {
                jCheckBox1.setSelected(false);
                idPhotose2.setSelected(false);
            }

        }

        double cashAmount = 0;
        double checkAmount = 0;

        ArrayList<CashModel> cashModels = gETOrderModel.getCashModels();
        for (CashModel cashModel : cashModels) {
            cashAmount += Double.parseDouble(cashModel.getCashAmount());
        }
        ArrayList<CheckModel> checkModels = gETOrderModel.getCheckModels();
        for (CheckModel checkModel : checkModels) {
            checkAmount += Double.parseDouble(checkModel.getAmount());
        }

        double totalPaid = cashAmount + checkAmount;
        paidAmountText.setText(CurrancyFormat.getCurrancyFormat(totalPaid));

        String orderAmount = gETOrderModel.getOrderModel().getOrderAmount();
        double balance = Double.parseDouble(orderAmount) - totalPaid;
        balanceA = balance;

        balanceAmountText.setText(CurrancyFormat.getCurrancyFormat(balance));

        if (leasingModel != null) {
            String snCharg = leasingModel.getSnCharge();
            snChargeText.setText(snCharg);

            leasingAmountA = balance + Double.parseDouble(snCharg);
            garanerDetail.setText(leasingModel.getGaranter());

            leasignCombo1.setSelectedItem(leasingModel.getLeasingName());

        } else {
            leasingAmountA = balance;
        }

        leasingAmountText.setText(CurrancyFormat.getCurrancyFormat(leasingAmountA));

    }

}
