/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.dialog;

import com.incosyz.sms.clientcontroller.SaleControllerImplClient;
import com.incosyz.sms.model.CashModel;
import com.incosyz.sms.model.CheckModel;
import com.incosyz.sms.model.LeasingModel;
import com.incosyz.sms.other.CurrancyFormat;
import com.incosyz.sms.other.Requirment;
import com.incosyz.sms.other.Validation;
import static com.incosyz.sms.view.Home.img;
import com.incosyz.sms.view.ManageCheque;
import java.awt.Color;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 * Date : Nov 4, 2015 Time : 12:16:05 AM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class SettlePayment extends javax.swing.JDialog {

    boolean cashPayment = false;
    boolean chequePayment = false;
    boolean leasingPayment = false;

    /**
     * Creates new form AddCustomer
     */
    public SettlePayment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        setIconImage(img);
        lPanel.setVisible(false);
        checkTableModel = (DefaultTableModel) checkTable.getModel();
        snLeasingPanel.setVisible(true);
        leasingPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        checkNoText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bankNameCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        checkCombo = new org.jdesktop.swingx.JXDatePicker();
        amountText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addOption = new javax.swing.JButton();
        addOption1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkTable = new javax.swing.JTable();
        lPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        leasingAmountText = new javax.swing.JTextField();
        addOption3 = new javax.swing.JButton();
        leasignCombo = new javax.swing.JComboBox();
        snLeasingPanel = new javax.swing.JPanel();
        mta2Check = new javax.swing.JCheckBox();
        mtaCheck = new javax.swing.JCheckBox();
        doCheck = new javax.swing.JCheckBox();
        gapCheck = new javax.swing.JCheckBox();
        gsCheck = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        garanerDetail = new javax.swing.JTextArea();
        leasingPanel = new javax.swing.JPanel();
        mta3Check = new javax.swing.JCheckBox();
        do2Check = new javax.swing.JCheckBox();
        idCopyCheck = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cashAmountText = new javax.swing.JTextField();
        addOption2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        leasingAmountLabel = new javax.swing.JLabel();
        cashAmountLabel = new javax.swing.JLabel();
        checkAmountLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        totalAmountText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        haveToSettle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        doneButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        settledPayment = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Settle Payments");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 20, 210, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Sales Management System -> Create New Sale ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 50, 310, 30);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cheque Payments"));
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cheque No :");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(30, 30, 200, 30);
        jPanel6.add(checkNoText);
        checkNoText.setBounds(30, 60, 190, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cheque Date :");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(240, 30, 200, 30);

        bankNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amana Bank PLC", "Axis Bank Ltd.", "Bank of Ceylon", "Cargills Bank Ltd.", "Citibank N.A.", "Commercial Bank of Ceylon PLC", "Deutsche Bank AG", "DFCC Bank PLC", "Habib Bank Ltd.", "Hatton National Bank PLC", "ICICI Bank Ltd.", "Indian Bank", "Indian Overseas Bank", "National Development Bank PLC", "Nations Trust Bank PLC", "Pan Asia Banking Corporation PLC", "People's Bank", "Public Bank Berhad", "Sampath Bank PLC", "Seylan Bank PLC", "Standard Chartered Bank", "Union Bank of Colombo PLC" }));
        jPanel6.add(bankNameCombo);
        bankNameCombo.setBounds(30, 120, 190, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Bank Name :");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(30, 90, 190, 30);
        jPanel6.add(checkCombo);
        checkCombo.setBounds(240, 60, 190, 30);

        amountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextActionPerformed(evt);
            }
        });
        amountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountTextKeyReleased(evt);
            }
        });
        jPanel6.add(amountText);
        amountText.setBounds(240, 120, 190, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Amount :");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(240, 90, 200, 30);

        addOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/add.jpg"))); // NOI18N
        addOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOptionActionPerformed(evt);
            }
        });
        jPanel6.add(addOption);
        addOption.setBounds(390, 160, 40, 30);

        addOption1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/delete.jpg"))); // NOI18N
        addOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOption1ActionPerformed(evt);
            }
        });
        jPanel6.add(addOption1);
        addOption1.setBounds(350, 160, 40, 30);

        checkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cheque No ", "Bank Name", "Date", "Check Amount"
            }
        ));
        checkTable.setRowHeight(25);
        checkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(checkTable);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 400, 110);

        backgroundPanel.add(jPanel6);
        jPanel6.setBounds(220, 0, 460, 340);

        lPanel.setBackground(new java.awt.Color(255, 255, 255));
        lPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Leasing "));
        lPanel.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Amount :");
        lPanel.add(jLabel13);
        jLabel13.setBounds(20, 30, 160, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Select leasing :");
        lPanel.add(jLabel14);
        jLabel14.setBounds(20, 90, 160, 30);

        leasingAmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                leasingAmountTextKeyReleased(evt);
            }
        });
        lPanel.add(leasingAmountText);
        leasingAmountText.setBounds(20, 60, 190, 30);

        addOption3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/add.jpg"))); // NOI18N
        addOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOption3ActionPerformed(evt);
            }
        });
        lPanel.add(addOption3);
        addOption3.setBounds(170, 300, 40, 30);

        leasignCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SN Leasing", "Other Leasing" }));
        leasignCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leasignComboActionPerformed(evt);
            }
        });
        lPanel.add(leasignCombo);
        leasignCombo.setBounds(20, 120, 190, 30);

        snLeasingPanel.setBackground(new java.awt.Color(255, 255, 255));
        snLeasingPanel.setLayout(null);

        mta2Check.setBackground(new java.awt.Color(255, 255, 255));
        mta2Check.setText("  MTA3");
        snLeasingPanel.add(mta2Check);
        mta2Check.setBounds(0, 30, 81, 23);

        mtaCheck.setBackground(new java.awt.Color(255, 255, 255));
        mtaCheck.setText("  MTA2");
        snLeasingPanel.add(mtaCheck);
        mtaCheck.setBounds(0, 10, 81, 23);

        doCheck.setBackground(new java.awt.Color(255, 255, 255));
        doCheck.setText("  DO");
        snLeasingPanel.add(doCheck);
        doCheck.setBounds(0, 50, 81, 23);

        gapCheck.setBackground(new java.awt.Color(255, 255, 255));
        gapCheck.setText("  GAP");
        snLeasingPanel.add(gapCheck);
        gapCheck.setBounds(100, 30, 81, 23);

        gsCheck.setBackground(new java.awt.Color(255, 255, 255));
        gsCheck.setText("  GS");
        snLeasingPanel.add(gsCheck);
        gsCheck.setBounds(100, 10, 81, 23);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Garanter Detail :");
        snLeasingPanel.add(jLabel17);
        jLabel17.setBounds(0, 80, 160, 20);

        garanerDetail.setColumns(20);
        garanerDetail.setRows(5);
        jScrollPane3.setViewportView(garanerDetail);

        snLeasingPanel.add(jScrollPane3);
        jScrollPane3.setBounds(0, 100, 190, 40);

        lPanel.add(snLeasingPanel);
        snLeasingPanel.setBounds(20, 150, 190, 150);

        leasingPanel.setBackground(new java.awt.Color(255, 255, 255));
        leasingPanel.setLayout(null);

        mta3Check.setBackground(new java.awt.Color(255, 255, 255));
        mta3Check.setText("  MTA3");
        mta3Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mta3CheckActionPerformed(evt);
            }
        });
        leasingPanel.add(mta3Check);
        mta3Check.setBounds(0, 10, 81, 23);

        do2Check.setBackground(new java.awt.Color(255, 255, 255));
        do2Check.setText("  DO");
        leasingPanel.add(do2Check);
        do2Check.setBounds(0, 30, 81, 23);

        idCopyCheck.setBackground(new java.awt.Color(255, 255, 255));
        idCopyCheck.setText("  ID Copy");
        leasingPanel.add(idCopyCheck);
        idCopyCheck.setBounds(100, 10, 81, 23);

        lPanel.add(leasingPanel);
        leasingPanel.setBounds(20, 150, 190, 60);

        backgroundPanel.add(lPanel);
        lPanel.setBounds(690, 0, 230, 340);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Cash Payments"));
        jPanel8.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Amount :");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(20, 100, 160, 30);

        cashAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashAmountTextActionPerformed(evt);
            }
        });
        cashAmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashAmountTextKeyReleased(evt);
            }
        });
        jPanel8.add(cashAmountText);
        cashAmountText.setBounds(20, 130, 170, 30);

        addOption2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/add.jpg"))); // NOI18N
        addOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOption2ActionPerformed(evt);
            }
        });
        jPanel8.add(addOption2);
        addOption2.setBounds(150, 170, 40, 30);

        backgroundPanel.add(jPanel8);
        jPanel8.setBounds(0, 0, 210, 340);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Leasing Amount :");
        backgroundPanel.add(jLabel2);
        jLabel2.setBounds(700, 350, 210, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cash amount :");
        backgroundPanel.add(jLabel3);
        jLabel3.setBounds(10, 350, 200, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cheque Amount :");
        backgroundPanel.add(jLabel4);
        jLabel4.setBounds(240, 350, 210, 20);

        leasingAmountLabel.setBackground(new java.awt.Color(255, 51, 51));
        leasingAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        leasingAmountLabel.setForeground(new java.awt.Color(255, 51, 51));
        leasingAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leasingAmountLabel.setText("Rs 0.00");
        backgroundPanel.add(leasingAmountLabel);
        leasingAmountLabel.setBounds(700, 370, 190, 40);

        cashAmountLabel.setBackground(new java.awt.Color(255, 51, 51));
        cashAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cashAmountLabel.setForeground(new java.awt.Color(255, 51, 51));
        cashAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cashAmountLabel.setText("Rs 0.00");
        backgroundPanel.add(cashAmountLabel);
        cashAmountLabel.setBounds(10, 370, 190, 40);

        checkAmountLabel.setBackground(new java.awt.Color(255, 51, 51));
        checkAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        checkAmountLabel.setForeground(new java.awt.Color(255, 51, 51));
        checkAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checkAmountLabel.setText("Rs 0.00");
        backgroundPanel.add(checkAmountLabel);
        checkAmountLabel.setBounds(240, 370, 190, 40);

        jPanel1.add(backgroundPanel);
        backgroundPanel.setBounds(20, 110, 920, 410);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Total Amount :");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 0, 120, 30);

        totalAmountText.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        totalAmountText.setForeground(new java.awt.Color(102, 102, 102));
        totalAmountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalAmountText.setText("217,900.00");
        jPanel4.add(totalAmountText);
        totalAmountText.setBounds(10, 20, 140, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(390, 10, 160, 60);

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(null);

        haveToSettle.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        haveToSettle.setForeground(new java.awt.Color(255, 51, 0));
        haveToSettle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        haveToSettle.setText("0.00");
        jPanel3.add(haveToSettle);
        haveToSettle.setBounds(10, 20, 150, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Have to Settle :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 0, 130, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(730, 10, 160, 60);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/done.jpg"))); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel2.add(doneButton);
        doneButton.setBounds(830, 10, 110, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/cancel.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(710, 10, 110, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 530, 960, 80);

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));
        jPanel5.setLayout(null);

        settledPayment.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        settledPayment.setForeground(new java.awt.Color(102, 102, 102));
        settledPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settledPayment.setText("Rs 0.00");
        jPanel5.add(settledPayment);
        settledPayment.setBounds(10, 20, 150, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Payment Settled :");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 0, 130, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(560, 10, 160, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed

        CashModel cashModel = null;
        if (cashPayment) {
            cashModel = new CashModel();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            cashModel.setCashAmount(String.valueOf(cashAmount));
            cashModel.setCashDate(dateFormat.format(new Date()));
        }

        ArrayList<CheckModel> checkModels = null;
        if (chequePayment) {
            checkModels = new ArrayList<>();
            for (int i = 0; i < checkTableModel.getRowCount(); i++) {
                String chequeNo = (String) checkTableModel.getValueAt(i, 0);
                String bankName = (String) checkTableModel.getValueAt(i, 1);
                String date = (String) checkTableModel.getValueAt(i, 2);
                String amount = (String) checkTableModel.getValueAt(i, 3);

                CheckModel checkModel = new CheckModel();
                checkModel.setCheckNo(chequeNo);
                checkModel.setBankName(bankName);
                checkModel.setChequeDate(date);
                checkModel.setAmount(amount);
                checkModel.setStateName("");

                checkModels.add(checkModel);
            }
        }

        LeasingModel leasingModel = null;
        if (leasingPayment) {
            String gs = gsCheck.isSelected() ? "1" : "0";
            String mta = mtaCheck.isSelected() ? "1" : "0";
            String mta2 = mta2Check.isSelected() ? "1" : "0";
            String gap = gapCheck.isSelected() ? "1" : "0";
            String doNo = doCheck.isSelected() ? "1" : "0";

            String mta3 = mta3Check.isSelected() ? "1" : "0";
            String idCopy = idCopyCheck.isSelected() ? "1" : "0";
            String doNo2 = do2Check.isSelected() ? "1" : "0";

            leasingModel = new LeasingModel();
            leasingModel.setLeasingAmount(String.valueOf(leasingAmount));
            leasingModel.setGaranter(garanerDetail.getText());
            String leasingName = "0";
            if (leasignCombo.getSelectedItem().equals("SN Leasing")) {
                leasingName = "1";
            }
            leasingModel.setLeasingName(leasingName);
            if (leasignCombo.getSelectedItem().equals("SN Leasing")) {
                leasingModel.setDoNo(doNo);
                leasingModel.setGap(gap);
                leasingModel.setMta(mta);
                leasingModel.setMta2(mta2);
                leasingModel.setGs(gs);
                leasingModel.setMta3("0");
                leasingModel.setIdCopy("0");
                leasingModel.setDoNo2("0");
            } else {
                leasingModel.setMta3(mta3);
                leasingModel.setIdCopy(idCopy);
                leasingModel.setDoNo2(doNo2);
                leasingModel.setDoNo("0");
                leasingModel.setGap("0");
                leasingModel.setMta("0");
                leasingModel.setMta2("0");
                leasingModel.setGs("0");
            }
        }

        manageSaleDetail.setPaymentDetail(cashModel, checkModels, leasingModel);
        manageSaleDetail.setPaidHaveSettle(settledPayment.getText(), haveToSettle.getText(), haveToSettlePayment);
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void addOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOptionActionPerformed
        JTextField field = amountText;
        if (field.getForeground() != Color.RED) {
            double myText = Double.parseDouble(field.getText());
            if (haveToSettlePayment < myText) {
                JOptionPane.showMessageDialog(this, "You can enter maximum cheque amount is : " + haveToSettle.getText() + "   ");
                return;
            }
        }

        if (amountText.getForeground() == Color.RED) {
            JOptionPane.showMessageDialog(this, "Input Data is Wrong format. Check Amount Details !");
        } else {

            boolean isExists = false;
            boolean isExistsDB = false;
            String chequeNo = checkNoText.getText();
            CheckModel cheque = null;
            try {
                cheque = SaleControllerImplClient.getCheque(chequeNo);
                if (cheque != null) {
                    isExistsDB = true;
                }
            } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(SettlePayment.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (!isExistsDB) {
                for (int i = 0; i < checkTable.getRowCount(); i++) {
                    String chequeNoInTable = (String) checkTableModel.getValueAt(i, 0);
                    if (chequeNoInTable.trim().equals(chequeNo)) {
                        isExists = true;
                        break;
                    }
                }

                if (isExists) {
                    JOptionPane.showMessageDialog(this, "Cheque Number is already Exists !");
                } else {
                    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    Date date = checkCombo.getDate();

                    String chequeDate = dateFormat.format(date);
                    String bankName = (String) bankNameCombo.getSelectedItem();
                    String amount = amountText.getText();

                    Object[] row = {chequeNo, bankName, chequeDate, amount};
                    checkTableModel.addRow(row);
                    setCheckAmountLabel();
                    amountText.setText("");
                    checkNoText.setText("");
                    checkNoText.requestFocus();
                }
                chequePayment = true;
                getSettledAmount();
            } else {
                int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Cheque is already added. Do you want to check ?");
                if (showConfirmDialog == JOptionPane.YES_OPTION) {
                    ManageCheque manageCheque = new ManageCheque(cheque);
                    manageCheque.setPaymentFrame(this);
                    manageCheque.setVisible(true);
//                    this.dispose();
                    this.setVisible(false);
                }
            }
        }

        if (haveToSettlePayment == 0) {
            haveToSettle.setForeground(new Color(0, 204, 102));
        } else {
            haveToSettle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addOptionActionPerformed

    private void addOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOption1ActionPerformed
        if (checkTable.getSelectedRow() > -1) {
            checkTableModel.removeRow(checkTable.getSelectedRow());
            setCheckAmountLabel();
            getSettledAmount();
        } else {
            JOptionPane.showMessageDialog(this, "Select row to delete !");
        }

        if (haveToSettlePayment == 0) {
            haveToSettle.setForeground(new Color(0, 204, 102));
        } else {
            haveToSettle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addOption1ActionPerformed

    private void checkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTableMouseClicked

    }//GEN-LAST:event_checkTableMouseClicked

    private void addOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOption2ActionPerformed
        JTextField field = cashAmountText;
        if (field.getForeground() != Color.RED) {
            double myText = Double.parseDouble(field.getText());
            if (haveToSettlePayment < myText) {
                JOptionPane.showMessageDialog(this, "You can enter maximum cash amount is : " + haveToSettle.getText() + "   ");
                return;
            }
        }

        if (cashAmountText.getForeground() == Color.RED) {
            JOptionPane.showMessageDialog(this, "Input data is wrong format !");
        } else {

            cashAmount = Double.parseDouble(cashAmountText.getText());
            cashPayment = true;
            cashAmountLabel.setText("Rs " + CurrancyFormat.getCurrancyFormat(cashAmount));
            getSettledAmount();
        }

        if (haveToSettlePayment == 0) {
            haveToSettle.setForeground(new Color(0, 204, 102));
        } else {
            haveToSettle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addOption2ActionPerformed

    private void addOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOption3ActionPerformed
        JTextField field = leasingAmountText;
        if (field.getForeground() != Color.RED) {
            double myText = Double.parseDouble(field.getText());
            if (haveToSettlePayment < myText) {
                JOptionPane.showMessageDialog(this, "You can enter maximum leasing amount is : " + haveToSettle.getText() + "   ");
                return;
            }
        }

        if (leasingAmountText.getForeground() == Color.RED) {
            JOptionPane.showMessageDialog(this, "Input data is wrong format. Check amount Details !");
        } else {

            leasingAmount = Double.parseDouble(leasingAmountText.getText());
            leasingAmountLabel.setText("Rs " + CurrancyFormat.getCurrancyFormat(leasingAmount));
            getSettledAmount();
            leasingPayment = true;
        }

        if (haveToSettlePayment == 0) {
            haveToSettle.setForeground(new Color(0, 204, 102));
        } else {
            haveToSettle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addOption3ActionPerformed

    private void mta3CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mta3CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mta3CheckActionPerformed

    private void leasignComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leasignComboActionPerformed
        String leasignName = (String) leasignCombo.getSelectedItem();
        if (leasignName.equals("SN Leasing")) {
            snLeasingPanel.setVisible(true);
            leasingPanel.setVisible(false);
        } else {
            leasingPanel.setVisible(true);
            snLeasingPanel.setVisible(false);
        }
    }//GEN-LAST:event_leasignComboActionPerformed

    private void cashAmountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashAmountTextKeyReleased
        Validation v = new Validation();
        v.inputCurrancy(cashAmountText);

        JTextField field = cashAmountText;
        if (field.getForeground() != Color.RED) {
            double myText = Double.parseDouble(field.getText());
            if (haveToSettlePayment < myText) {
                field.setForeground(Color.red);
            } else {
                field.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_cashAmountTextKeyReleased

    private void amountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextKeyReleased
        Validation v = new Validation();
        v.inputCurrancy(amountText);

        JTextField field = amountText;
        if (field.getForeground() != Color.RED) {
            double myText = Double.parseDouble(field.getText());
            if (haveToSettlePayment < myText) {
                field.setForeground(Color.red);
            } else {
                field.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_amountTextKeyReleased

    private void leasingAmountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leasingAmountTextKeyReleased
        Validation v = new Validation();
        v.inputCurrancy(leasingAmountText);

        JTextField field = leasingAmountText;
        if (field.getForeground() != Color.RED) {
            double myText = Double.parseDouble(field.getText());
            if (haveToSettlePayment < myText) {
                field.setForeground(Color.red);
            } else {
                field.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_leasingAmountTextKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cashAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashAmountTextActionPerformed
        addOption2.doClick();
    }//GEN-LAST:event_cashAmountTextActionPerformed

    private void amountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextActionPerformed
        addOption.doClick();
    }//GEN-LAST:event_amountTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettlePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettlePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettlePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettlePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettlePayment dialog = new SettlePayment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOption;
    private javax.swing.JButton addOption1;
    private javax.swing.JButton addOption2;
    private javax.swing.JButton addOption3;
    private javax.swing.JTextField amountText;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox bankNameCombo;
    private javax.swing.JLabel cashAmountLabel;
    private javax.swing.JTextField cashAmountText;
    private javax.swing.JLabel checkAmountLabel;
    private org.jdesktop.swingx.JXDatePicker checkCombo;
    private javax.swing.JTextField checkNoText;
    private javax.swing.JTable checkTable;
    private javax.swing.JCheckBox do2Check;
    private javax.swing.JCheckBox doCheck;
    private javax.swing.JButton doneButton;
    private javax.swing.JCheckBox gapCheck;
    private javax.swing.JTextArea garanerDetail;
    private javax.swing.JCheckBox gsCheck;
    private javax.swing.JLabel haveToSettle;
    private javax.swing.JCheckBox idCopyCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel lPanel;
    private javax.swing.JComboBox leasignCombo;
    private javax.swing.JLabel leasingAmountLabel;
    private javax.swing.JTextField leasingAmountText;
    private javax.swing.JPanel leasingPanel;
    private javax.swing.JCheckBox mta2Check;
    private javax.swing.JCheckBox mta3Check;
    private javax.swing.JCheckBox mtaCheck;
    private javax.swing.JLabel settledPayment;
    private javax.swing.JPanel snLeasingPanel;
    private javax.swing.JLabel totalAmountText;
    // End of variables declaration//GEN-END:variables

    private ManageSaleDetail manageSaleDetail;
    private double totalAmount;
    private double haveToSettlePayment;
    private DefaultTableModel checkTableModel;
    private double checkAmount;
    private double cashAmount;
    private double leasingAmount;

    public void setFrame(ManageSaleDetail manageSaleDetail) {
        this.manageSaleDetail = manageSaleDetail;
    }

    public void setAmountPaid(double totalAmount, ArrayList<CashModel> cashModels, ArrayList<CheckModel> checkModels, LeasingModel leasingModel) {
        this.totalAmount = totalAmount;
        totalAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(totalAmount));
        haveToSettle.setText("Rs " + CurrancyFormat.getCurrancyFormat(totalAmount));

        Requirment r = new Requirment(cashModels, checkModels, leasingModel);
        double paidAmount = r.getTotalAmount();
        this.haveToSettlePayment = totalAmount - paidAmount;
        settledPayment.setText("Rs " + CurrancyFormat.getCurrancyFormat(paidAmount));
        haveToSettle.setText("Rs " + CurrancyFormat.getCurrancyFormat(totalAmount - paidAmount));

        this.checkAmount = r.getChequeAmount();
        this.cashAmount = r.getCashAmount();
        this.leasingAmount = r.getLeasing();

        cashAmountLabel.setText("Rs " + CurrancyFormat.getCurrancyFormat(cashAmount));
        checkAmountLabel.setText("Rs " + CurrancyFormat.getCurrancyFormat(checkAmount));
        leasingAmountLabel.setText("Rs " + CurrancyFormat.getCurrancyFormat(leasingAmount));
    }

    public void setDetail(double totalAmount) {
        this.totalAmount = totalAmount;
        this.haveToSettlePayment = totalAmount;
        totalAmountText.setText("Rs " + CurrancyFormat.getCurrancyFormat(totalAmount));
        haveToSettle.setText("Rs " + CurrancyFormat.getCurrancyFormat(totalAmount));
    }

    public double setCheckAmountLabel() {
        double checkTot = 0;
        for (int i = 0; i < checkTableModel.getRowCount(); i++) {
            checkTot += Double.parseDouble((String) checkTableModel.getValueAt(i, 3));
        }
        checkAmount = checkTot;
        checkAmountLabel.setText("Rs " + CurrancyFormat.getCurrancyFormat(checkTot));
        return checkTot;
    }

    public double getSettledAmount() {
        double settledAmount = checkAmount + cashAmount + leasingAmount;
        settledPayment.setText("Rs " + CurrancyFormat.getCurrancyFormat(settledAmount));
        this.haveToSettlePayment = totalAmount - settledAmount;
        haveToSettle.setText("Rs " + CurrancyFormat.getCurrancyFormat(haveToSettlePayment));
        return settledAmount;
    }

    public void leasingFalse() {
        lPanel.setVisible(false);
        jLabel2.setVisible(false);
        leasingAmountLabel.setVisible(false);
    }

    public void leasingTrue() {
        lPanel.setVisible(false);
        jLabel2.setVisible(true);
        leasingAmountLabel.setVisible(true);
    }
}
