/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.dialog;

import com.incosyz.sms.clientcontroller.ChequeControllerClient;
import com.incosyz.sms.clientcontroller.FileControllerClient;
import com.incosyz.sms.clientcontroller.Generator;
import com.incosyz.sms.model.CheckModel;
import com.incosyz.sms.view.ManageCheque;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Date : Nov 11, 2015 Time : 11:15:28 PM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class UpdateChequeDetail extends javax.swing.JDialog {

    /**
     * Creates new form AddNewCheque
     */
    public UpdateChequeDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkNoText = new javax.swing.JTextField();
        payLabel = new javax.swing.JLabel();
        issuedByText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        dateText = new org.jdesktop.swingx.JXDatePicker();
        typeText = new javax.swing.JComboBox();
        bankNameText = new javax.swing.JComboBox();
        accountNoText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        issued = new javax.swing.JRadioButton();
        received = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chequeNote = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        filePathText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Samagi Traders - Update Cheque Detail");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 550, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sales Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 230, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cheque NO :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 200, 30);

        checkNoText.setEditable(false);
        jPanel1.add(checkNoText);
        checkNoText.setBounds(30, 130, 210, 30);

        payLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payLabel.setText("From :");
        jPanel1.add(payLabel);
        payLabel.setBounds(30, 170, 200, 30);
        jPanel1.add(issuedByText);
        issuedByText.setBounds(30, 200, 210, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Amount :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 240, 200, 30);
        jPanel1.add(amountText);
        amountText.setBounds(30, 270, 210, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 310, 200, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Bank Name :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 170, 200, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("State :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 240, 200, 30);
        jPanel1.add(stateText);
        stateText.setBounds(300, 270, 210, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Type :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(300, 310, 200, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/cancel.jpg"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 450, 110, 50);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/updateCheque.jpg"))); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);
        addButton.setBounds(670, 450, 110, 50);

        dateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(dateText);
        dateText.setBounds(30, 340, 210, 30);

        typeText.setEditable(true);
        typeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeText.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash Cheque", "Order Cheque", "Uncrossed / Open Cheque", "Crossed Cheque", "Date Cheque", "Stale Cheque", "Payee Cheque" }));
        jPanel1.add(typeText);
        typeText.setBounds(300, 340, 210, 30);

        bankNameText.setEditable(true);
        bankNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bankNameText.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amana Bank PLC", "Axis Bank Ltd.", "Bank of Ceylon", "Cargills Bank Ltd.", "Citibank N.A.", "Commercial Bank of Ceylon PLC", "Deutsche Bank AG", "DFCC Bank PLC", "Habib Bank Ltd.", "Hatton National Bank PLC", "ICICI Bank Ltd.", "Indian Bank", "Indian Overseas Bank", "National Development Bank PLC", "Nations Trust Bank PLC", "Pan Asia Banking Corporation PLC", "People's Bank", "Public Bank Berhad", "Sampath Bank PLC", "Seylan Bank PLC", "Standard Chartered Bank", "Union Bank of Colombo PLC" }));
        jPanel1.add(bankNameText);
        bankNameText.setBounds(300, 200, 210, 30);
        jPanel1.add(accountNoText);
        accountNoText.setBounds(300, 130, 210, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Note :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(570, 100, 200, 30);

        issued.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(issued);
        issued.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issued.setText("   Issued Cheque");
        issued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedActionPerformed(evt);
            }
        });
        jPanel1.add(issued);
        issued.setBounds(570, 320, 170, 20);

        received.setBackground(new java.awt.Color(250, 250, 250));
        buttonGroup1.add(received);
        received.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        received.setSelected(true);
        received.setText("   Received Cheque");
        received.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedActionPerformed(evt);
            }
        });
        jPanel1.add(received);
        received.setBounds(570, 350, 170, 20);

        chequeNote.setColumns(20);
        chequeNote.setRows(5);
        jScrollPane1.setViewportView(chequeNote);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(570, 130, 210, 80);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Account No :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(300, 100, 200, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/incosyz/sms/image/browse.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(740, 260, 40, 30);

        filePathText.setEditable(false);
        filePathText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(filePathText);
        filePathText.setBounds(570, 260, 160, 30);

        jLabel3.setText("Cheque Copy ( JPEG , PNG ) :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(570, 230, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean canAdd = true;

        String isIssued = "0";
        if (issued.isSelected()) {
            isIssued = "1";
        }

        if (checkNoText.getText().trim().equals("")) {
            canAdd = false;
        }

        if (amountText.getText().trim().equals("")) {
            canAdd = false;
        }

        if (canAdd) {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                String generateId = checkModel.getChequeId();

                String type = "";

                if (typeText.getSelectedItem() != null) {
                    type = typeText.getSelectedItem().toString();
                }

                CheckModel checkModel = new CheckModel()
                        .setChequeId(generateId)
                        .setCheckNo(checkNoText.getText())
                        .setIssuedBy(issuedByText.getText())
                        .setAmount(amountText.getText())
                        .setChequeDate(dateFormat.format(dateText.getDate()))
                        .setAccountNo(accountNoText.getText())
                        .setBankName(bankNameText.getSelectedItem().toString())
                        .setStateName(stateText.getText())
                        .setType(type)
                        .setIsIssued(isIssued)
                        .setNote(chequeNote.getText());

                boolean addCheque = ChequeControllerClient.updateCheque(checkModel);
                if (addCheque) {
                    File file = new File(filePath);
                    if (file.isFile()) {
                        byte[] buffer = null;
                        try {
                            InputStream inputStream = new FileInputStream(file);
                            buffer = new byte[inputStream.available()];
                            inputStream.read(buffer);

                            boolean saveFile = FileControllerClient.saveFile("IMG" + generateId + ".cms", buffer);
                        } catch (IOException | NotBoundException ex) {
                            Logger.getLogger(AddNewCheque.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    
                    JOptionPane.showMessageDialog(this, "Cheque detail updated !");
                    manageCheque.getCheque();
                    dispose();
                }
            } catch (NotBoundException | MalformedURLException | ClassNotFoundException | SQLException | RemoteException ex) {
                Logger.getLogger(UpdateChequeDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cheque no & Amount is required. check again !");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void issuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedActionPerformed
//        issuedByText.setEnabled(true);
        payLabel.setText("To ( Pay ) :");
    }//GEN-LAST:event_issuedActionPerformed

    private void receivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedActionPerformed
//        issuedByText.setEnabled(false);
        payLabel.setText("From :");
    }//GEN-LAST:event_receivedActionPerformed
    String filePath = "";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            filePath = fileChooser.getSelectedFile().getPath();
            filePathText.setText(fileChooser.getSelectedFile().getName());

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateChequeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateChequeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateChequeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateChequeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateChequeDetail dialog = new UpdateChequeDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNoText;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountText;
    private javax.swing.JComboBox bankNameText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField checkNoText;
    private javax.swing.JTextArea chequeNote;
    private org.jdesktop.swingx.JXDatePicker dateText;
    private javax.swing.JTextField filePathText;
    private javax.swing.JRadioButton issued;
    private javax.swing.JTextField issuedByText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel payLabel;
    private javax.swing.JRadioButton received;
    private javax.swing.JTextField stateText;
    private javax.swing.JComboBox typeText;
    // End of variables declaration//GEN-END:variables

    private ManageCheque manageCheque;
    private CheckModel checkModel;

    public void setParentFrame(ManageCheque manageCheque) {
        this.manageCheque = manageCheque;
    }

    public void setChequeModel(CheckModel checkModel) {
        this.checkModel = checkModel;
        checkNoText.setText(checkModel.getCheckNo());
        issuedByText.setText(checkModel.getIssuedBy());
        amountText.setText(checkModel.getAmount());

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = dateFormat.parse(checkModel.getChequeDate());
            dateText.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateChequeDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        accountNoText.setText(checkModel.getAccountNo());
        bankNameText.setSelectedItem(checkModel.getBankName());
        stateText.setText(checkModel.getStateName());
        typeText.setSelectedItem(checkModel.getType());
        chequeNote.setText(checkModel.getNote());

        if (checkModel.getIsIssued().equals("1")) {
            issued.setSelected(true);
        }
    }

}
