/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.incosyz.sms.panel;

import com.incosyz.sms.clientcontroller.CustomerControllerImplClient;
import com.incosyz.sms.clientcontroller.Generator;
import com.incosyz.sms.dialog.EditSale;
import com.incosyz.sms.mixmodel.GETOrderModel;
import com.incosyz.sms.model.CashModel;
import com.incosyz.sms.model.CheckModel;
import com.incosyz.sms.model.CustomerModel;
import com.incosyz.sms.model.PaymentModel;
import com.incosyz.sms.other.CurrancyFormat;
import java.util.ArrayList;

/**
 * Date : Nov 16, 2015 Time : 6:41:03 PM
 *
 * @copyright INCOSYZ
 * @author Stelan
 */
public class DocumentPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditCustomerPanel
     */
    public DocumentPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private EditSale editSale;
    private GETOrderModel gETOrderModel;

    public void setFrame(EditSale editSale) {
        this.editSale = editSale;
    }

    public void setDetail(GETOrderModel gETOrderModel) {
        this.gETOrderModel = gETOrderModel;
        
    }
}
